# Explanations: what the app will say about each lounge and area

Each decision (`../scorecard.ipynb`, `../growth.ipynb`) gets a pyramid: a one-sentence answer, then the arguments that
matter most for it (ranked by `src.explain.prioritize`, never by the writer), each backed by 2-5
numbers copied from the decision's fact sheet. `src.explain.verify` rejects any explanation that
cites a value or writes a number not on the fact sheet.

The **AI** explanations here were written in a Claude Code session from the same prompts
`just explain` sends to the API (`python -m src.explain prompts|check|ingest`), so no API credits
were spent; they are cached in `data/explanations/cache.json` by a hash of their fact sheet, so a
changed number falls back to the deterministic **template**. The NOT SCORED airport lounge and
SKIP areas always use the template.

Data: `src.explain.v3_subjects()` (baseline, medium levels).

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while not (ROOT / "pyproject.toml").exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

from collections import Counter

import pandas as pd
from IPython.display import Markdown, display

from src.explain import (LOUNGE_TABLE, AREA_TABLE, explain, load_cache, table_rows,
                         v3_subjects, verify)

pd.set_option("display.max_colwidth", 120)
cache = load_cache()
subjects = v3_subjects()
exps = {(k, sid): explain(k, sid, a, f, cache=cache) for k, sid, a, f in subjects}
facts = {(k, sid): f for k, sid, a, f in subjects}
print(Counter((k, e.source) for (k, _), e in exps.items()))
print("grounding failures:", sum(bool(verify(e, facts[key], key[0])) for key, e in exps.items()))

Counter({('area', 'template'): 464, ('area', 'ai'): 97, ('lounge', 'ai'): 23, ('uae', 'ai'): 1, ('lounge', 'template'): 1})
grounding failures: 0

In [2]:
def show(kind, sid):
    e, f = exps[(kind, sid)], facts[(kind, sid)]
    lines = [f"### {sid} — **{e.action}** ({e.source})", "", f"**{e.headline}**", ""]
    for r in e.reasons:
        ev = "; ".join(f"{x.label}: {x.value}" for x in r.evidence)
        lines += [f"- **{r.topic}**: {r.claim}  \n  <small>{ev}</small>"]
    lines += ["", f"_{e.table_caption}_"]
    display(Markdown("\n".join(lines)))


def table(kind, sid):
    fields = {"lounge": LOUNGE_TABLE, "area": AREA_TABLE}[kind]
    return pd.DataFrame(table_rows(fields, facts[(kind, sid)])).set_index("Factor")

## The network summary (the app opens with this)

In [3]:
show("uae", "uae")

### uae — **SUMMARY** (ai)

**6 PROTECT, 14 HOLD and 3 SHRINK across 23 scored lounges, each judged against its own emirate's salon sites, with 34 areas to GROW.**

- **shrink**: Investigate al-jada, city-walk, westyas: their sites are weak for their emirates on rent or demand (strongest SHRINK composite 0.35).
  <small>SHRINK: 3; SHRINK lounges: al-jada, city-walk, westyas; Strongest SHRINK composite: 0.348</small>
- **grow**: 34 areas would each add 6,000+ net new women at a site that out-serves half its emirate's salon sites and costs no more than their median rent (or has only the emirate median rent, then low confidence), 796,024 women 15+ between them.
  <small>GROW: 34; Women in GROW areas: 796024; Closest GROW area to a lounge: 1.3018; Furthest GROW area from a lounge: 54.9537</small>
- **protect**: Defend al-ain, al-dhafra, al-falah, al-taif-mall, mirdif-35, nad-al-sheba: strong sites for their emirates (weakest PROTECT composite 0.66, al-falah, on a neutral fallback rent).
  <small>PROTECT: 6; PROTECT lounges: al-ain, al-dhafra, al-falah, al-taif-mall, mirdif-35, nad-al-sheba; Weakest PROTECT composite: 0.6645</small>
- **confidence**: 14 of 23 lounges sit in the HOLD band and 11 calls are low confidence (near a line, sensitive to the assumptions or weights, or on an emirate-median rent).
  <small>HOLD: 14; Low-confidence calls: 11; Lounges scored: 23</small>
- **data_gaps**: No revenue, lease or footfall data: these are location and market calls, built on 3,833 salons found by search.
  <small>Revenue data: False; Lease data: False; Salons searched: 3833</small>

_Lounge calls rank each site within its emirate's frozen market of competitor salon sites, on demand and rent; growth areas are what-if new lounges tested on net new women, demand and rent._

## Lounges, PROTECT first

In [4]:
order = {"PROTECT": 0, "HOLD": 1, "SHRINK": 2, "NOT SCORED": 3}
for k, sid, a, f in sorted((s for s in subjects if s[0] == "lounge"), key=lambda s: (order[s[2]], s[1])):
    show(k, sid)

### al-ain — **PROTECT** (ai)

**PROTECT: al-ain's site would out-serve 95% of Abu Dhabi salon sites on demand; its rent is only the Abu Dhabi median, scored neutral, so the call is low confidence (composite 0.72).**

- **demand**: A typical lounge at this site would serve about 10,173 women, more than it would at 95% of Abu Dhabi salon sites; 93rd percentile UAE-wide.
  <small>Site demand percentile: 0.9474; Demand percentile UAE-wide: 0.9323; Women a typical lounge would serve here: 10173.4578; Demand score: 0.9474</small>
- **cost**: Its site rent of AED 1,168/m² a year is the Abu Dhabi median standing in for a cell with no rent of its own, not the site's, so rent scores neutral (0.5); for context it is dearer than 22% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent at the site: 1168.0; Cost score: 0.5; Rent percentile UAE-wide: 0.2155</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### al-dhafra — **PROTECT** (ai)

**PROTECT: al-dhafra's site would out-serve 100% of Abu Dhabi salon sites on demand, with a rent about level with the median salon site in its emirate (composite 0.76).**

- **demand**: A typical lounge at this site would serve about 22,852 women, more than it would at 100% of Abu Dhabi salon sites; 100th percentile UAE-wide.
  <small>Site demand percentile: 1.0; Demand percentile UAE-wide: 0.9955; Women a typical lounge would serve here: 22851.8054; Demand score: 1.0</small>
- **cost**: Shop rent of AED 1,339/m² a year gives a rent ratio of 1.04, about level with the median salon site in its emirate; dearer than 32% of UAE salon sites.
  <small>Rent ratio: 1.0411; Rent percentile UAE-wide: 0.3188; Shop rent at the site: 1339.0; Cost score: 0.5219</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### al-falah — **PROTECT** (ai)

**PROTECT: al-falah's site would out-serve 83% of Abu Dhabi salon sites on demand; its rent is only the Abu Dhabi median, scored neutral, so the call is low confidence (composite 0.66).**

- **demand**: A typical lounge at this site would serve about 7,866 women, more than it would at 83% of Abu Dhabi salon sites; 85th percentile UAE-wide.
  <small>Site demand percentile: 0.8289; Demand percentile UAE-wide: 0.8522; Women a typical lounge would serve here: 7865.5012; Demand score: 0.8289</small>
- **cost**: Its site rent of AED 1,168/m² a year is the Abu Dhabi median standing in for a cell with no rent of its own, not the site's, so rent scores neutral (0.5); for context it is dearer than 22% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent at the site: 1168.0; Cost score: 0.5; Rent percentile UAE-wide: 0.2155</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### al-taif-mall — **PROTECT** (ai)

**PROTECT: al-taif-mall's site would out-serve 90% of UAE salon sites on demand, with a rent cheaper than the median salon site in its emirate (composite 0.95).**

- **cost**: Shop rent of AED 481/m² a year gives a rent ratio of 1.55, cheaper than the median salon site in its emirate; among the cheapest UAE salon sites.
  <small>Rent ratio: 1.5506; Rent percentile UAE-wide: 0.0045; Shop rent at the site: 480.6; Cost score: 1.0</small>
- **demand**: A typical lounge at this site would serve about 8,980 women, more than it would at 90% of UAE salon sites (under 50 reference sites in its emirate, so ranked UAE-wide); 90th percentile UAE-wide.
  <small>Site demand percentile: 0.9003; Demand percentile UAE-wide: 0.9003; Women a typical lounge would serve here: 8980.4181; Demand score: 0.9003</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### mirdif-35 — **PROTECT** (ai)

**PROTECT: mirdif-35's site would out-serve 98% of Dubai salon sites on demand, with a rent cheaper than the median salon site in its emirate (composite 0.79).**

- **demand**: A typical lounge at this site would serve about 5,388 women, more than it would at 98% of Dubai salon sites; 75th percentile UAE-wide.
  <small>Site demand percentile: 0.9845; Demand percentile UAE-wide: 0.7498; Women a typical lounge would serve here: 5388.3446; Demand score: 0.9845</small>
- **cost**: Shop rent of AED 1,957/m² a year gives a rent ratio of 1.10, cheaper than the median salon site in its emirate; dearer than 58% of UAE salon sites.
  <small>Rent ratio: 1.1004; Rent percentile UAE-wide: 0.5815; Shop rent at the site: 1957.0; Cost score: 0.595</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### nad-al-sheba — **PROTECT** (ai)

**PROTECT: nad-al-sheba's site would out-serve 68% of Dubai salon sites on demand, with a rent cheaper than the median salon site in its emirate (composite 0.71).**

- **cost**: Shop rent of AED 1,784/m² a year gives a rent ratio of 1.21, cheaper than the median salon site in its emirate; dearer than 55% of UAE salon sites.
  <small>Rent ratio: 1.2071; Rent percentile UAE-wide: 0.5503; Shop rent at the site: 1784.0; Cost score: 0.7265</small>
- **demand**: A typical lounge at this site would serve about 2,670 women, more than it would at 68% of Dubai salon sites; 48th percentile UAE-wide.
  <small>Site demand percentile: 0.6838; Demand percentile UAE-wide: 0.4809; Women a typical lounge would serve here: 2670.1653; Demand score: 0.6838</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### al-barsha — **HOLD** (ai)

**HOLD: al-barsha's site would out-serve 42% of Dubai salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.39).**

- **cost**: Shop rent of AED 2,381/m² a year gives a rent ratio of 0.90, dearer than the median salon site in its emirate; dearer than 83% of UAE salon sites.
  <small>Rent ratio: 0.9045; Rent percentile UAE-wide: 0.8317; Shop rent at the site: 2381.0; Cost score: 0.3535</small>
- **demand**: A typical lounge at this site would serve about 2,192 women, more than it would at 42% of Dubai salon sites; 33rd percentile UAE-wide.
  <small>Site demand percentile: 0.421; Demand percentile UAE-wide: 0.3268; Women a typical lounge would serve here: 2191.6443; Demand score: 0.421</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### al-maqta — **HOLD** (ai)

**HOLD: al-maqta's site would out-serve 52% of Abu Dhabi salon sites on demand, with a rent about level with the median salon site in its emirate (composite 0.52).**

- **demand**: A typical lounge at this site would serve about 4,159 women, more than it would at 52% of Abu Dhabi salon sites; 67th percentile UAE-wide.
  <small>Site demand percentile: 0.5197; Demand percentile UAE-wide: 0.6696; Women a typical lounge would serve here: 4159.1128; Demand score: 0.5197</small>
- **cost**: Shop rent of AED 1,348/m² a year gives a rent ratio of 1.03, about level with the median salon site in its emirate; dearer than 33% of UAE salon sites.
  <small>Rent ratio: 1.0341; Rent percentile UAE-wide: 0.333; Shop rent at the site: 1348.0; Cost score: 0.5133</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### baniyas — **HOLD** (ai)

**HOLD: baniyas's site would out-serve 99% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.54).**

- **demand**: A typical lounge at this site would serve about 13,036 women, more than it would at 99% of Abu Dhabi salon sites; 98th percentile UAE-wide.
  <small>Site demand percentile: 0.9901; Demand percentile UAE-wide: 0.9777; Women a typical lounge would serve here: 13036.4522; Demand score: 0.9901</small>
- **cost**: Shop rent of AED 2,003/m² a year gives a rent ratio of 0.70, dearer than the median salon site in its emirate; dearer than 62% of UAE salon sites.
  <small>Rent ratio: 0.696; Rent percentile UAE-wide: 0.6198; Shop rent at the site: 2003.0; Cost score: 0.0966</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### delma — **HOLD** (ai)

**HOLD: delma's site would out-serve 38% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.38).**

- **demand**: A typical lounge at this site would serve about 1,895 women, more than it would at 38% of Abu Dhabi salon sites; 25th percentile UAE-wide.
  <small>Site demand percentile: 0.375; Demand percentile UAE-wide: 0.2538; Women a typical lounge would serve here: 1894.7771; Demand score: 0.375</small>
- **cost**: Shop rent of AED 1,507/m² a year gives a rent ratio of 0.93, dearer than the median salon site in its emirate; dearer than 40% of UAE salon sites.
  <small>Rent ratio: 0.925; Rent percentile UAE-wide: 0.3998; Shop rent at the site: 1507.0; Cost score: 0.3789</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### jumeirah-park — **HOLD** (ai)

**HOLD: jumeirah-park's site would out-serve 44% of Dubai salon sites on demand, with a rent about level with the median salon site in its emirate (composite 0.47).**

- **demand**: A typical lounge at this site would serve about 2,234 women, more than it would at 44% of Dubai salon sites; 34th percentile UAE-wide.
  <small>Site demand percentile: 0.445; Demand percentile UAE-wide: 0.3393; Women a typical lounge would serve here: 2233.9451; Demand score: 0.445</small>
- **cost**: Shop rent of AED 2,118/m² a year gives a rent ratio of 1.02, about level with the median salon site in its emirate; dearer than 66% of UAE salon sites.
  <small>Rent ratio: 1.0168; Rent percentile UAE-wide: 0.6625; Shop rent at the site: 2118.0; Cost score: 0.4919</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### khaleej-al-arabi — **HOLD** (ai)

**HOLD: khaleej-al-arabi's site would out-serve 22% of Abu Dhabi salon sites on demand, with a rent about level with the median salon site in its emirate (composite 0.350).**

- **demand**: A typical lounge at this site would serve about 1,359 women, more than it would at 22% of Abu Dhabi salon sites; 11th percentile UAE-wide.
  <small>Site demand percentile: 0.2171; Demand percentile UAE-wide: 0.1077; Women a typical lounge would serve here: 1358.5882; Demand score: 0.2171</small>
- **cost**: Shop rent of AED 1,380/m² a year gives a rent ratio of 1.01, about level with the median salon site in its emirate; dearer than 34% of UAE salon sites.
  <small>Rent ratio: 1.0101; Rent percentile UAE-wide: 0.3411; Shop rent at the site: 1380.0; Cost score: 0.4838</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### khalifa-city-a — **HOLD** (ai)

**HOLD: khalifa-city-a's site would out-serve 73% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.36).**

- **cost**: Shop rent of AED 2,257/m² a year gives a rent ratio of 0.62, dearer than the median salon site in its emirate; dearer than 76% of UAE salon sites.
  <small>Rent ratio: 0.6176; Rent percentile UAE-wide: 0.7605; Shop rent at the site: 2257.0; Cost score: 0.0</small>
- **demand**: A typical lounge at this site would serve about 6,144 women, more than it would at 73% of Abu Dhabi salon sites; 78th percentile UAE-wide.
  <small>Site demand percentile: 0.727; Demand percentile UAE-wide: 0.7827; Women a typical lounge would serve here: 6144.209; Demand score: 0.727</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### ministries-complex — **HOLD** (ai)

**HOLD: ministries-complex's site would out-serve 50% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.359).**

- **cost**: Shop rent of AED 1,756/m² a year gives a rent ratio of 0.79, dearer than the median salon site in its emirate; dearer than 54% of UAE salon sites.
  <small>Rent ratio: 0.7938; Rent percentile UAE-wide: 0.5414; Shop rent at the site: 1756.0; Cost score: 0.2172</small>
- **demand**: A typical lounge at this site would serve about 3,919 women, more than it would at 50% of Abu Dhabi salon sites; 65th percentile UAE-wide.
  <small>Site demand percentile: 0.5; Demand percentile UAE-wide: 0.6536; Women a typical lounge would serve here: 3919.1981; Demand score: 0.5</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### mohammed-bin-zayed-city — **HOLD** (ai)

**HOLD: mohammed-bin-zayed-city's site would out-serve 59% of Abu Dhabi salon sites on demand, with a rent cheaper than the median salon site in its emirate (composite 0.61).**

- **cost**: Shop rent of AED 1,236/m² a year gives a rent ratio of 1.13, cheaper than the median salon site in its emirate; dearer than 26% of UAE salon sites.
  <small>Rent ratio: 1.1278; Rent percentile UAE-wide: 0.26; Shop rent at the site: 1236.0; Cost score: 0.6288</small>
- **demand**: A typical lounge at this site would serve about 4,581 women, more than it would at 59% of Abu Dhabi salon sites; 70th percentile UAE-wide.
  <small>Site demand percentile: 0.5855; Demand percentile UAE-wide: 0.7026; Women a typical lounge would serve here: 4580.6939; Demand score: 0.5855</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### noya-plaza — **HOLD** (ai)

**HOLD: noya-plaza's site would out-serve 52% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.38).**

- **cost**: Shop rent of AED 1,707/m² a year gives a rent ratio of 0.82, dearer than the median salon site in its emirate; dearer than 52% of UAE salon sites.
  <small>Rent ratio: 0.8166; Rent percentile UAE-wide: 0.5165; Shop rent at the site: 1707.0; Cost score: 0.2453</small>
- **demand**: A typical lounge at this site would serve about 4,228 women, more than it would at 52% of Abu Dhabi salon sites; 67th percentile UAE-wide.
  <small>Site demand percentile: 0.523; Demand percentile UAE-wide: 0.6741; Women a typical lounge would serve here: 4227.6929; Demand score: 0.523</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### ras-al-khaimah — **HOLD** (ai)

**HOLD: ras-al-khaimah's site would out-serve 86% of UAE salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.50).**

- **cost**: Shop rent of AED 1,172/m² a year gives a rent ratio of 0.73, dearer than the median salon site in its emirate; dearer than 23% of UAE salon sites.
  <small>Rent ratio: 0.7275; Rent percentile UAE-wide: 0.2306; Shop rent at the site: 1172.0; Cost score: 0.1354</small>
- **demand**: A typical lounge at this site would serve about 7,946 women, more than it would at 86% of UAE salon sites (under 50 reference sites in its emirate, so ranked UAE-wide); 86th percentile UAE-wide.
  <small>Site demand percentile: 0.8566; Demand percentile UAE-wide: 0.8566; Women a typical lounge would serve here: 7945.9976; Demand score: 0.8566</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### shahama — **HOLD** (ai)

**HOLD: shahama's site would out-serve 93% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.57).**

- **demand**: A typical lounge at this site would serve about 9,865 women, more than it would at 93% of Abu Dhabi salon sites; 92nd percentile UAE-wide.
  <small>Site demand percentile: 0.9276; Demand percentile UAE-wide: 0.9243; Women a typical lounge would serve here: 9865.3121; Demand score: 0.9276</small>
- **cost**: Shop rent of AED 1,747/m² a year gives a rent ratio of 0.80, dearer than the median salon site in its emirate; dearer than 54% of UAE salon sites.
  <small>Rent ratio: 0.7979; Rent percentile UAE-wide: 0.5396; Shop rent at the site: 1747.0; Cost score: 0.2223</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### shakhbout-city — **HOLD** (ai)

**HOLD: shakhbout-city's site would out-serve 87% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.53).**

- **demand**: A typical lounge at this site would serve about 8,685 women, more than it would at 87% of Abu Dhabi salon sites; 89th percentile UAE-wide.
  <small>Site demand percentile: 0.8717; Demand percentile UAE-wide: 0.8914; Women a typical lounge would serve here: 8685.0314; Demand score: 0.8717</small>
- **cost**: Shop rent of AED 1,815/m² a year gives a rent ratio of 0.77, dearer than the median salon site in its emirate; dearer than 56% of UAE salon sites.
  <small>Rent ratio: 0.768; Rent percentile UAE-wide: 0.5592; Shop rent at the site: 1815.0; Cost score: 0.1854</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### zawaya-walk — **HOLD** (ai)

**HOLD: zawaya-walk's site would out-serve 58% of Sharjah salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.41).**

- **cost**: Shop rent of AED 1,389/m² a year gives a rent ratio of 0.81, dearer than the median salon site in its emirate; dearer than 36% of UAE salon sites.
  <small>Rent ratio: 0.8071; Rent percentile UAE-wide: 0.3562; Shop rent at the site: 1389.1; Cost score: 0.2335</small>
- **demand**: A typical lounge at this site would serve about 7,569 women, more than it would at 58% of Sharjah salon sites; 83rd percentile UAE-wide.
  <small>Site demand percentile: 0.5804; Demand percentile UAE-wide: 0.8344; Women a typical lounge would serve here: 7568.9551; Demand score: 0.5804</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### al-jada — **SHRINK** (ai)

**SHRINK: al-jada's site would out-serve 66% of Sharjah salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.34).**

- **cost**: Shop rent of AED 1,771/m² a year gives a rent ratio of 0.63, dearer than the median salon site in its emirate; dearer than 54% of UAE salon sites.
  <small>Rent ratio: 0.6331; Rent percentile UAE-wide: 0.5423; Shop rent at the site: 1770.8; Cost score: 0.0191</small>
- **demand**: A typical lounge at this site would serve about 7,912 women, more than it would at 66% of Sharjah salon sites; 85th percentile UAE-wide.
  <small>Site demand percentile: 0.6573; Demand percentile UAE-wide: 0.8531; Women a typical lounge would serve here: 7912.2548; Demand score: 0.6573</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### city-walk — **SHRINK** (ai)

**SHRINK: city-walk's site would out-serve 30% of Dubai salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.15).**

- **cost**: Shop rent of AED 4,561/m² a year gives a rent ratio of 0.47, dearer than the median salon site in its emirate; dearer than 98% of UAE salon sites.
  <small>Rent ratio: 0.4722; Rent percentile UAE-wide: 0.9849; Shop rent at the site: 4561.0; Cost score: 0.0</small>
- **demand**: A typical lounge at this site would serve about 1,905 women, more than it would at 30% of Dubai salon sites; 26th percentile UAE-wide.
  <small>Site demand percentile: 0.3024; Demand percentile UAE-wide: 0.2591; Women a typical lounge would serve here: 1905.0265; Demand score: 0.3024</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### westyas — **SHRINK** (ai)

**SHRINK: westyas's site would out-serve 45% of Abu Dhabi salon sites on demand, with a rent dearer than the median salon site in its emirate (composite 0.348).**

- **cost**: Shop rent of AED 1,707/m² a year gives a rent ratio of 0.82, dearer than the median salon site in its emirate; dearer than 52% of UAE salon sites.
  <small>Rent ratio: 0.8166; Rent percentile UAE-wide: 0.5165; Shop rent at the site: 1707.0; Cost score: 0.2453</small>
- **demand**: A typical lounge at this site would serve about 3,259 women, more than it would at 45% of Abu Dhabi salon sites; 57th percentile UAE-wide.
  <small>Site demand percentile: 0.4507; Demand percentile UAE-wide: 0.5672; Women a typical lounge would serve here: 3259.3995; Demand score: 0.4507</small>

_Both scored signals rank this lounge's site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve, and the rent ratio is their median shop rent over this site's (above 1 is cheaper). The UAE-wide percentiles are context; served women, capture, rating and the shared catchment are shown, not scored._

### zayed-international-airport — **NOT SCORED** (template)

**Not scored: this lounge serves travellers, not the women living around it, so the catchment model doesn't apply.**

- **demand**: Site demand percentile: n/a (missing), shown but not scored.
  <small>Site demand percentile: None; Demand percentile UAE-wide: None; Demand ranked among: Abu Dhabi; Women a typical lounge would serve here: None; Women served (Huff): None</small>
- **capture**: Capture: 4% of reviews, shown but not scored.
  <small>Capture: 0.0392; Premium substitutes: 11; Premium salons in catchment: 51; Thin premium market: False</small>

_Each signal is scored 0-1 on a fixed scale, where 1 is good for the lounge, and the composite is their weighted average. Both rank the site within its emirate's frozen market of competitor salon sites: demand is the share of them a typical lounge here would out-serve (Huff); rent is their median shop rent over this site's. The lounge's own served women, as performance vs its site, capture, rating and the shared catchment are shown for context, not scored._

The factor table the app shows next to a lounge's pyramid, for one example:

In [5]:
table("lounge", "al-barsha")

,Value,Unit,Threshold,What it means
Factor,,,,
Site demand percentile,42%,% of salon sites,"Demand score: 0% of salon sites → 0, 100% of salon sites → 1; weight 1",Share of the reference salon sites in its emirate (UAE-wide under 50) that a typical lounge would out-serve at this ...
Demand ranked among,Dubai,,—,"Whose salon sites the demand percentile ranks against: the site's emirate, or UAE when the emirate has under 50 refe..."
Demand percentile UAE-wide,33%,% of UAE salon sites,—,"The same, against all 1,123 UAE reference salon sites. Context, not scored."
Women a typical lounge would serve here,"2,192",women,—,"What-if: the women a typical lounge (median reviews and rating) would serve at this site, with this lounge closed an..."
Women served (Huff),"2,180",women,—,Addressable women this lounge serves: its Huff share of every cell it reaches within 20 min. It rests on the lounge'...
Performance vs site,0.99,x its site,—,Women this lounge serves ÷ women a typical lounge would serve at its site. Read as 'The model estimates this lounge ...
Absorbed by siblings,1%,% of served,—,Share of its served women other lounges take over if it closes.
Women 15+ in catchment,"272,371",women,—,"Women aged 15+ living in the ~2 km cells within a 15-min drive (typical midday traffic). WorldPop adults, rebalanced..."
Addressable women 15+,"272,371",women,—,"Catchment women times an affluence weight (observed median rent vs the women-weighted median, to the affluence elast..."
Affluence rent,"115,000",AED/yr,—,"Median annual household rent (DLD Ejari contracts, Jul-Oct 2026), weighted by women, over the cells with an observed..."
Affluence coverage,99%,% of women,"Under 50%: affluence mostly unknown, weighted neutral",Share of the women here living in cells with an observed rent. The rest are weighted neutral: affluence unknown. Dub...
Cells in catchment,64,count,—,Populated ~2 km grid cells whose centre is within the drive time.
Shared catchment,86%,% of catchment women,—,Share of the catchment's women who live in cells another open Bedashing lounge also reaches: the cannibalisation mea...
Premium salons in catchment,228,count,—,"Google Places salons in the catchment that count as premium: Google price 'expensive' or above, or (unpriced) at lea..."
Premium saturation,551,reviews per 1k women,"Unsaturated under 150 (context, not a test)","Premium salons' Google reviews (scaled up for missed salons) per 1,000 women in the searched cells: the same measure..."
Rent ratio,0.9,,"Cost score: 0.62 → 0, 1.43 → 1; weight 1",Median shop rent at the reference salon sites in its emirate ÷ this site's shop rent: above 1 is cheaper than a typi...
Rent percentile UAE-wide,83%,% of UAE salon sites,—,"Share of the UAE reference salon sites with a lower shop rent (higher = dearer). Context, not scored."
Shop rent at the site,"2,381",AED/m²/yr,—,"Commercial (shop) rent where the lounge sits: our cost, not customer affluence. Dubai: the median of DLD Ejari shop ..."
Women per AED 1k of rent,763,women,—,"Addressable women per AED 1,000 of annual rent for a 150 m² unit (assumed): the unit size sets the level, never the ..."
Premium substitutes,63,count,—,The most-reviewed premium salons that together hold 60% of the catchment's premium reviews: the lounge's real compet...
Capture,1%,% of reviews,—,"Lounge reviews ÷ (lounge + substitutes' reviews, scaled up for salons the search missed). A proxy for share of premi..."
Thin premium market,no,yes/no,"Context: capture is shown, not scored","Fewer than 10 premium salons: capture of a tiny pool is noisy. Capture is shown, not scored."
Google rating,4.6,stars (of 5),—,The lounge's Google rating.
Google reviews,753,count,—,Reviews behind the lounge's rating.
Premium salons' median rating,4.8,stars (of 5),—,Median Google rating of the premium salons in the catchment with 20+ reviews.
Rating gap,-0.2,stars,—,Lounge rating minus the median rating of the premium salons in its catchment (20+ reviews).
Assumption sensitivity,0,of 81 combinations,Low confidence at 27 or more,"How many of the 81 combinations of travel time, competitor coverage, worker-housing share and affluence weighting ch..."
Composite score,0.39,0-1,PROTECT ≥ 0.65 · HOLD between · SHRINK ≤ 0.35,"Weighted average of the signal scores below (weights in the Threshold column). PROTECT ≥ 0.65, SHRINK ≤ 0.35. Keep o..."
Demand score,0.42,0-1,Weight 1 of 2,"Site demand: share of its emirate's salon sites it out-serves, converted to a fixed 0-1 score where 1 is best for th..."
Cost score,0.35,0-1,Weight 1 of 2,"Site rent: emirate median shop rent at salon sites ÷ this site's, converted to a fixed 0-1 score where 1 is best for..."
Site cost,447,AED 1k/yr,—,"Shop rent x 150 m² (assumed unit) + fit-out of AED 3,000/m² over 5 years (assumed)."
Demand contribution,0.21,0-1,Sums to the composite (max 0.50),What the demand score adds to the composite: weight × score ÷ total weight. The 2 contributions sum to the composite.
Cost contribution,0.18,0-1,Sums to the composite (max 0.50),What the cost score adds to the composite: weight × score ÷ total weight. The 2 contributions sum to the composite.
Nearest other call,SHRINK,,—,The call this lounge would get if its composite crossed the nearest line.
Distance to that line,0.04,0-1,—,How far the composite would have to move to reach the nearest other call.
Driver that could flip it,cost,,—,"The highest-ranked location or market signal that, moving alone, could carry the composite across that line (rating ..."
Value that flips it,0.84,,—,"The value of that driver's input (in its own unit) at which the call changes, all else equal."

## Growth areas: GROW, then WATCH by women

In [6]:
areas = sorted((s for s in subjects if s[0] == "area" and s[2] != "SKIP"),
               key=lambda s: (s[2] != "GROW", -s[3]["women"]))
for k, sid, a, f in areas:
    show(k, sid)

### sharjah-sharjah — **GROW** (ai)

**GROW Sharjah: a new lounge would add about 12,800 net new women, out-serve 90% of Sharjah salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 13,176 women, take 368 from our lounges and add 12,808 net, 6,808 above the 6,000 line.
  <small>Net new women: 12808.3802; New lounge would serve: 13176.3868; Taken from our lounges: 368.0067; Size gap: 6808</small>
- **demand**: That is more than a typical lounge would serve at 90% of Sharjah salon sites, 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9021; Demand gap: 0.4021; Demand percentile UAE-wide: 0.9777; New lounge would serve: 13176.3868</small>
- **cost**: Shop rent of AED 1,121/m² a year gives a rent ratio of 1.00 against the median Sharjah salon site, exactly on the 1 line; dearer than 20% of UAE salon sites.
  <small>Rent ratio: 1.0; Rent gap: 0.0; Rent percentile UAE-wide: 0.195; Shop rent in the area: 1121.1</small>
- **reach**: Our al-jada lounge is only 2.5 km away in a straight line, yet a new site would take just 368 women from our lounges.
  <small>Distance to nearest lounge: 2.4824; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-dhaid-sharjah — **GROW** (ai)

**GROW Al Dhaid: a new lounge would add about 57,900 net new women and out-serve 100% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 57,932 women and take almost none from our lounges, so 57,932 are net new, 51,932 above the 6,000 line.
  <small>Net new women: 57931.7203; New lounge would serve: 57931.7203; Taken from our lounges: 0.0; Size gap: 51932</small>
- **demand**: That is more than a typical lounge would serve at 100% of Sharjah salon sites, 100th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 1.0; Demand gap: 0.5; Demand percentile UAE-wide: 1.0; New lounge would serve: 57931.7203</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, al-jada, is 43.8 km away: Al Dhaid is white space for the network.
  <small>Distance to nearest lounge: 43.7824; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### kalba-sharjah — **GROW** (ai)

**GROW Kalba: a new lounge would add about 12,500 net new women and out-serve 90% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 13,329 women, take 871 from our lounges and add 12,459 net, 6,459 above the 6,000 line.
  <small>Net new women: 12458.6472; New lounge would serve: 13329.2141; Taken from our lounges: 870.5669; Size gap: 6459</small>
- **demand**: That is more than a typical lounge would serve at 90% of Sharjah salon sites, 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9021; Demand gap: 0.4021; Demand percentile UAE-wide: 0.9786; New lounge would serve: 13329.2141</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, al-taif-mall, is 9.0 km away in a straight line.
  <small>Distance to nearest lounge: 9.0015; Nearest lounge: al-taif-mall</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-madam-sharjah — **GROW** (ai)

**GROW Al Madam: a new lounge would add about 19,700 net new women and out-serve 94% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 19,728 women and take almost none from our lounges, so 19,728 are net new, 13,728 above the 6,000 line.
  <small>Net new women: 19727.7719; New lounge would serve: 19727.7719; Taken from our lounges: 0.0; Size gap: 13728</small>
- **demand**: That is more than a typical lounge would serve at 94% of Sharjah salon sites, 99th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9441; Demand gap: 0.4441; Demand percentile UAE-wide: 0.9929; New lounge would serve: 19727.7719</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, mirdif-35, is 46.7 km away: Al Madam is white space for the network.
  <small>Distance to nearest lounge: 46.7161; Nearest lounge: mirdif-35</small>
- **data_gap**: Our salon search covered only 37% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.3662; Coverage needed: 0.5; Coverage gap: -0.1338</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### khor-fakkan-sharjah — **GROW** (ai)

**GROW Khor Fakkan: a new lounge would add about 23,400 net new women and out-serve 97% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 23,433 women, take 8 from our lounges and add 23,424 net, 17,424 above the 6,000 line.
  <small>Net new women: 23424.3675; New lounge would serve: 23432.6178; Taken from our lounges: 8.2504; Size gap: 17424</small>
- **demand**: That is more than a typical lounge would serve at 97% of Sharjah salon sites, 100th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.972; Demand gap: 0.472; Demand percentile UAE-wide: 0.9964; New lounge would serve: 23432.6178</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, al-taif-mall, is 26.5 km away in a straight line.
  <small>Distance to nearest lounge: 26.5027; Nearest lounge: al-taif-mall</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-jerf-ajman — **GROW** (ai)

**GROW Al Jerf: a new lounge would add about 12,500 net new women, out-serve 98% of UAE salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 12,642 women, take 108 from our lounges and add 12,534 net, 6,534 above the 6,000 line.
  <small>Net new women: 12533.8104; New lounge would serve: 12642.1293; Taken from our lounges: 108.3189; Size gap: 6534</small>
- **demand**: That is more than a typical lounge would serve at 98% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9777; Demand gap: 0.4777; Demand percentile UAE-wide: 0.9777; New lounge would serve: 12642.1293</small>
- **cost**: Shop rent of AED 674/m² a year gives a rent ratio of 1.12 against the median Ajman salon site, 0.12 above the 1 line; dearer than 3% of UAE salon sites.
  <small>Rent ratio: 1.1175; Rent gap: 0.1175; Rent percentile UAE-wide: 0.0303; Shop rent in the area: 673.8</small>
- **reach**: The nearest lounge, al-jada, is 12.2 km away in a straight line.
  <small>Distance to nearest lounge: 12.2148; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### hamidiya-ajman — **GROW** (ai)

**GROW Hamidiya: a new lounge would add about 13,400 net new women, out-serve 98% of UAE salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 13,536 women, take 149 from our lounges and add 13,386 net, 7,386 above the 6,000 line.
  <small>Net new women: 13386.4644; New lounge would serve: 13535.5336; Taken from our lounges: 149.0692; Size gap: 7386</small>
- **demand**: That is more than a typical lounge would serve at 98% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9795; Demand gap: 0.4795; Demand percentile UAE-wide: 0.9795; New lounge would serve: 13535.5336</small>
- **cost**: Shop rent of AED 753/m² a year gives a rent ratio of 1.000 against the median Ajman salon site, 0.001 above the 1 line; dearer than 7% of UAE salon sites.
  <small>Rent ratio: 1.0005; Rent gap: 0.0005; Rent percentile UAE-wide: 0.0659; Shop rent in the area: 752.6</small>
- **reach**: The nearest lounge, al-jada, is 10.6 km away in a straight line.
  <small>Distance to nearest lounge: 10.5919; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-batayih-sharjah — **GROW** (ai)

**GROW Al Batayih: a new lounge would add about 12,600 net new women and out-serve 90% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 12,572 women and take almost none from our lounges, so 12,572 are net new, 6,572 above the 6,000 line.
  <small>Net new women: 12571.657; New lounge would serve: 12571.657; Taken from our lounges: 0.0; Size gap: 6572</small>
- **demand**: That is more than a typical lounge would serve at 90% of Sharjah salon sites, 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8951; Demand gap: 0.3951; Demand percentile UAE-wide: 0.976; New lounge would serve: 12571.657</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, al-jada, is 28.8 km away in a straight line.
  <small>Distance to nearest lounge: 28.8131; Nearest lounge: al-jada</small>
- **data_gap**: Our salon search covered only 8% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0759; Coverage needed: 0.5; Coverage gap: -0.4241</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-awir-dubai — **GROW** (ai)

**GROW Al Awir: a new lounge would add about 7,100 net new women and out-serve 99% of Dubai salon sites; its rent is only the Dubai median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 7,239 women, take 133 from our lounges and add 7,106 net, 1,106 above the 6,000 line.
  <small>Net new women: 7106.2054; New lounge would serve: 7238.7569; Taken from our lounges: 132.5515; Size gap: 1106</small>
- **demand**: That is more than a typical lounge would serve at 99% of Dubai salon sites, 83rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.988; Demand gap: 0.488; Demand percentile UAE-wide: 0.8255; New lounge would serve: 7238.7569</small>
- **cost**: Shop rent of AED 1,985/m² a year is the Dubai median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 60% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1985.0; Rent percentile UAE-wide: 0.5975</small>
- **reach**: The nearest lounge, mirdif-35, is 13.6 km away in a straight line.
  <small>Distance to nearest lounge: 13.5915; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-hamriya-sharjah — **GROW** (ai)

**GROW Al Hamriya: a new lounge would add about 9,700 net new women and out-serve 80% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 9,774 women, take 43 from our lounges and add 9,731 net, 3,731 above the 6,000 line.
  <small>Net new women: 9731.476; New lounge would serve: 9774.2239; Taken from our lounges: 42.7479; Size gap: 3731</small>
- **demand**: That is more than a typical lounge would serve at 80% of Sharjah salon sites, 92nd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7972; Demand gap: 0.2972; Demand percentile UAE-wide: 0.9216; New lounge would serve: 9774.2239</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, al-jada, is 16.4 km away in a straight line.
  <small>Distance to nearest lounge: 16.4128; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### zakhir-abu-dhabi — **GROW** (ai)

**GROW Zakhir: a new lounge would add about 10,500 net new women, out-serve 98% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 11,204 women, take 677 from our lounges and add 10,528 net, 4,528 above the 6,000 line.
  <small>Net new women: 10527.6356; New lounge would serve: 11204.3702; Taken from our lounges: 676.7346; Size gap: 4528</small>
- **demand**: That is more than a typical lounge would serve at 98% of Abu Dhabi salon sites, 95th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.977; Demand gap: 0.477; Demand percentile UAE-wide: 0.951; New lounge would serve: 11204.3702</small>
- **cost**: Shop rent of AED 893/m² a year gives a rent ratio of 1.56 against the median Abu Dhabi salon site, 0.56 above the 1 line; dearer than 9% of UAE salon sites.
  <small>Rent ratio: 1.561; Rent gap: 0.561; Rent percentile UAE-wide: 0.0908; Shop rent in the area: 893.0</small>
- **reach**: The nearest lounge, al-ain, is 10.4 km away in a straight line.
  <small>Distance to nearest lounge: 10.4131; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-hiyar-abu-dhabi — **GROW** (ai)

**GROW Al Hiyar: a new lounge would add about 7,000 net new women, out-serve 78% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 6,958 women and take almost none from our lounges, so 6,958 are net new, 958 above the 6,000 line.
  <small>Net new women: 6957.9668; New lounge would serve: 6957.9668; Taken from our lounges: 0.0; Size gap: 958</small>
- **demand**: That is more than a typical lounge would serve at 78% of Abu Dhabi salon sites, 81st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7829; Demand gap: 0.2829; Demand percentile UAE-wide: 0.813; New lounge would serve: 6957.9668</small>
- **cost**: Shop rent of AED 1,056/m² a year gives a rent ratio of 1.32 against the median Abu Dhabi salon site, 0.32 above the 1 line; dearer than 15% of UAE salon sites.
  <small>Rent ratio: 1.3201; Rent gap: 0.3201; Rent percentile UAE-wide: 0.1469; Shop rent in the area: 1056.0</small>
- **reach**: The nearest lounge, al-ain, is 38.9 km away: Al Hiyar is white space for the network.
  <small>Distance to nearest lounge: 38.9419; Nearest lounge: al-ain</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### milehah-sharjah — **GROW** (ai)

**GROW Milehah: a new lounge would add about 18,500 net new women and out-serve 94% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 18,518 women, take 9 from our lounges and add 18,509 net, 12,509 above the 6,000 line.
  <small>Net new women: 18508.7449; New lounge would serve: 18518.1928; Taken from our lounges: 9.4479; Size gap: 12509</small>
- **demand**: That is more than a typical lounge would serve at 94% of Sharjah salon sites, 99th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9371; Demand gap: 0.4371; Demand percentile UAE-wide: 0.9911; New lounge would serve: 18518.1928</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, al-taif-mall, is 43.3 km away: Milehah is white space for the network.
  <small>Distance to nearest lounge: 43.2554; Nearest lounge: al-taif-mall</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-ramlah-sharjah — **GROW** (ai)

**GROW Al Ramlah: a new lounge would add about 12,600 net new women and out-serve 90% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 12,600 women, take 27 from our lounges and add 12,573 net, 6,573 above the 6,000 line.
  <small>Net new women: 12573.1891; New lounge would serve: 12600.1098; Taken from our lounges: 26.9208; Size gap: 6573</small>
- **demand**: That is more than a typical lounge would serve at 90% of Sharjah salon sites, 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8951; Demand gap: 0.3951; Demand percentile UAE-wide: 0.976; New lounge would serve: 12600.1098</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, al-jada, is 17.1 km away in a straight line.
  <small>Distance to nearest lounge: 17.0811; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### mzeer-ah-abu-dhabi — **GROW** (ai)

**GROW Mzeerʻah: a new lounge would add about 7,700 net new women, out-serve 81% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 7,670 women and take almost none from our lounges, so 7,670 are net new, 1,670 above the 6,000 line.
  <small>Net new women: 7669.9842; New lounge would serve: 7669.9842; Taken from our lounges: 0.0; Size gap: 1670</small>
- **demand**: That is more than a typical lounge would serve at 81% of Abu Dhabi salon sites, 84th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8092; Demand gap: 0.3092; Demand percentile UAE-wide: 0.8397; New lounge would serve: 7669.9842</small>
- **cost**: Shop rent of AED 166/m² a year gives a rent ratio of 8.40 against the median Abu Dhabi salon site, 7.40 above the 1 line; among the cheapest UAE salon sites.
  <small>Rent ratio: 8.3976; Rent gap: 7.3976; Rent percentile UAE-wide: 0.0; Shop rent in the area: 166.0</small>
- **reach**: The nearest lounge, al-dhafra, is 55.0 km away: Mzeerʻah is white space for the network.
  <small>Distance to nearest lounge: 54.9537; Nearest lounge: al-dhafra</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### rimah-abu-dhabi — **GROW** (ai)

**GROW Rimah: a new lounge would add about 7,300 net new women, out-serve 81% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 7,484 women, take 162 from our lounges and add 7,322 net, 1,322 above the 6,000 line.
  <small>Net new women: 7322.0561; New lounge would serve: 7483.669; Taken from our lounges: 161.6129; Size gap: 1322</small>
- **demand**: That is more than a typical lounge would serve at 81% of Abu Dhabi salon sites, 83rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8059; Demand gap: 0.3059; Demand percentile UAE-wide: 0.8335; New lounge would serve: 7483.669</small>
- **cost**: Shop rent of AED 682/m² a year gives a rent ratio of 2.04 against the median Abu Dhabi salon site, 1.04 above the 1 line; dearer than 3% of UAE salon sites.
  <small>Rent ratio: 2.044; Rent gap: 1.044; Rent percentile UAE-wide: 0.0303; Shop rent in the area: 682.0</small>
- **reach**: The nearest lounge, al-ain, is 33.0 km away: Rimah is white space for the network.
  <small>Distance to nearest lounge: 32.985; Nearest lounge: al-ain</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### meshairef-ajman — **GROW** (ai)

**GROW Meshairef: a new lounge would add about 9,000 net new women, out-serve 91% of UAE salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 9,131 women, take 155 from our lounges and add 8,977 net, 2,977 above the 6,000 line.
  <small>Net new women: 8976.8199; New lounge would serve: 9131.45; Taken from our lounges: 154.6301; Size gap: 2977</small>
- **demand**: That is more than a typical lounge would serve at 91% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 91st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9074; Demand gap: 0.4074; Demand percentile UAE-wide: 0.9074; New lounge would serve: 9131.45</small>
- **cost**: Shop rent of AED 502/m² a year gives a rent ratio of 1.50 against the median Ajman salon site, 0.50 above the 1 line; dearer than 1% of UAE salon sites.
  <small>Rent ratio: 1.4991; Rent gap: 0.4991; Rent percentile UAE-wide: 0.0098; Shop rent in the area: 502.3</small>
- **reach**: The nearest lounge, zawaya-walk, is 9.5 km away in a straight line.
  <small>Distance to nearest lounge: 9.5148; Nearest lounge: zawaya-walk</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### falaj-hazza-abu-dhabi — **GROW** (ai)

**GROW Falaj Hazza': a new lounge would add about 8,200 net new women, out-serve 88% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 8,779 women, take 589 from our lounges and add 8,191 net, 2,191 above the 6,000 line.
  <small>Net new women: 8190.701; New lounge would serve: 8779.4981; Taken from our lounges: 588.7971; Size gap: 2191</small>
- **demand**: That is more than a typical lounge would serve at 88% of Abu Dhabi salon sites, 89th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8849; Demand gap: 0.3849; Demand percentile UAE-wide: 0.8949; New lounge would serve: 8779.4981</small>
- **cost**: Shop rent of AED 1,001/m² a year gives a rent ratio of 1.39 against the median Abu Dhabi salon site, 0.39 above the 1 line; dearer than 12% of UAE salon sites.
  <small>Rent ratio: 1.3926; Rent gap: 0.3926; Rent percentile UAE-wide: 0.1202; Shop rent in the area: 1001.0</small>
- **reach**: The nearest lounge, al-ain, is 7.7 km away in a straight line.
  <small>Distance to nearest lounge: 7.6777; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-maqam-abu-dhabi — **GROW** (ai)

**GROW Al Maqam: a new lounge would add about 8,900 net new women, out-serve 94% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 10,120 women, take 1,180 from our lounges and add 8,940 net, 2,940 above the 6,000 line.
  <small>Net new women: 8940.3943; New lounge would serve: 10120.0116; Taken from our lounges: 1179.6173; Size gap: 2940</small>
- **demand**: That is more than a typical lounge would serve at 94% of Abu Dhabi salon sites, 93rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9441; Demand gap: 0.4441; Demand percentile UAE-wide: 0.9305; New lounge would serve: 10120.0116</small>
- **cost**: Shop rent of AED 688/m² a year gives a rent ratio of 2.03 against the median Abu Dhabi salon site, 1.03 above the 1 line; dearer than 3% of UAE salon sites.
  <small>Rent ratio: 2.0262; Rent gap: 1.0262; Rent percentile UAE-wide: 0.0303; Shop rent in the area: 688.0</small>
- **reach**: The nearest lounge, al-ain, is 5.1 km away in a straight line.
  <small>Distance to nearest lounge: 5.1479; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### um-ghafah-abu-dhabi — **GROW** (ai)

**GROW Um Ghafah: a new lounge would add about 13,200 net new women, out-serve 99% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 13,207 women and take almost none from our lounges, so 13,207 are net new, 7,207 above the 6,000 line.
  <small>Net new women: 13207.2919; New lounge would serve: 13207.2919; Taken from our lounges: 0.0; Size gap: 7207</small>
- **demand**: That is more than a typical lounge would serve at 99% of Abu Dhabi salon sites, 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9901; Demand gap: 0.4901; Demand percentile UAE-wide: 0.9777; New lounge would serve: 13207.2919</small>
- **cost**: Shop rent of AED 304/m² a year gives a rent ratio of 4.59 against the median Abu Dhabi salon site, 3.59 above the 1 line; among the cheapest UAE salon sites.
  <small>Rent ratio: 4.5855; Rent gap: 3.5855; Rent percentile UAE-wide: 0.0; Shop rent in the area: 304.0</small>
- **reach**: The nearest lounge, al-ain, is 29.9 km away in a straight line.
  <small>Distance to nearest lounge: 29.9053; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-fahlain-ras-al-khaimah — **GROW** (ai)

**GROW Al Fahlain: a new lounge would add about 8,100 net new women and out-serve 88% of UAE salon sites; its rent is only the Ras Al Khaimah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 8,561 women, take 464 from our lounges and add 8,098 net, 2,098 above the 6,000 line.
  <small>Net new women: 8097.7471; New lounge would serve: 8561.3384; Taken from our lounges: 463.5913; Size gap: 2098</small>
- **demand**: That is more than a typical lounge would serve at 88% of UAE salon sites (Ras Al Khaimah has under 50, so ranked UAE-wide), 88th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8833; Demand gap: 0.3833; Demand percentile UAE-wide: 0.8833; New lounge would serve: 8561.3384</small>
- **cost**: Shop rent of AED 819/m² a year is the Ras Al Khaimah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 7% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 818.7; Rent percentile UAE-wide: 0.0739</small>
- **reach**: The nearest lounge, ras-al-khaimah, is 9.7 km away in a straight line.
  <small>Distance to nearest lounge: 9.6736; Nearest lounge: ras-al-khaimah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### digdaga-ras-al-khaimah — **GROW** (ai)

**GROW Digdaga: a new lounge would add about 6,800 net new women and out-serve 82% of UAE salon sites; its rent is only the Ras Al Khaimah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 7,075 women, take 253 from our lounges and add 6,823 net, 823 above the 6,000 line.
  <small>Net new women: 6822.9311; New lounge would serve: 7075.4529; Taken from our lounges: 252.5218; Size gap: 823</small>
- **demand**: That is more than a typical lounge would serve at 82% of UAE salon sites (Ras Al Khaimah has under 50, so ranked UAE-wide), 82nd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8192; Demand gap: 0.3192; Demand percentile UAE-wide: 0.8192; New lounge would serve: 7075.4529</small>
- **cost**: Shop rent of AED 819/m² a year is the Ras Al Khaimah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 7% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 818.7; Rent percentile UAE-wide: 0.0739</small>
- **reach**: The nearest lounge, ras-al-khaimah, is 10.8 km away in a straight line.
  <small>Distance to nearest lounge: 10.7873; Nearest lounge: ras-al-khaimah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### mudayrah-ajman — **GROW** (ai)

**GROW Mudayrah: a new lounge would add about 18,700 net new women and out-serve 99% of UAE salon sites; its rent is only the Ajman median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 18,651 women and take almost none from our lounges, so 18,651 are net new, 12,651 above the 6,000 line.
  <small>Net new women: 18651.4411; New lounge would serve: 18651.4411; Taken from our lounges: 0.0; Size gap: 12651</small>
- **demand**: That is more than a typical lounge would serve at 99% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 99th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.992; Demand gap: 0.492; Demand percentile UAE-wide: 0.992; New lounge would serve: 18651.4411</small>
- **cost**: Shop rent of AED 755/m² a year is the Ajman median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 7% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 755.0; Rent percentile UAE-wide: 0.073</small>
- **reach**: The nearest lounge, al-taif-mall, is 42.9 km away: Mudayrah is white space for the network.
  <small>Distance to nearest lounge: 42.9108; Nearest lounge: al-taif-mall</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-rahbah-abu-dhabi — **GROW** (ai)

**GROW Al Rahbah: a new lounge would add about 8,000 net new women, out-serve 96% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 10,463 women, take 2,472 from our lounges and add 7,991 net, 1,991 above the 6,000 line.
  <small>Net new women: 7990.899; New lounge would serve: 10462.5951; Taken from our lounges: 2471.696; Size gap: 1991</small>
- **demand**: That is more than a typical lounge would serve at 96% of Abu Dhabi salon sites, 94th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9572; Demand gap: 0.4572; Demand percentile UAE-wide: 0.9377; New lounge would serve: 10462.5951</small>
- **cost**: Shop rent of AED 198/m² a year gives a rent ratio of 7.04 against the median Abu Dhabi salon site, 6.04 above the 1 line; among the cheapest UAE salon sites.
  <small>Rent ratio: 7.0404; Rent gap: 6.0404; Rent percentile UAE-wide: 0.0; Shop rent in the area: 198.0</small>
- **reach**: The nearest lounge, shahama, is 8.4 km away in a straight line.
  <small>Distance to nearest lounge: 8.4198; Nearest lounge: shahama</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-sad-abu-dhabi — **GROW** (ai)

**GROW Al Sad: a new lounge would add about 7,000 net new women and out-serve 81% of Abu Dhabi salon sites; its rent is only the Abu Dhabi median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 7,608 women, take 618 from our lounges and add 6,989 net, 989 above the 6,000 line.
  <small>Net new women: 6989.3007; New lounge would serve: 7607.6019; Taken from our lounges: 618.3012; Size gap: 989</small>
- **demand**: That is more than a typical lounge would serve at 81% of Abu Dhabi salon sites, 84th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8059; Demand gap: 0.3059; Demand percentile UAE-wide: 0.8353; New lounge would serve: 7607.6019</small>
- **cost**: Shop rent of AED 1,168/m² a year is the Abu Dhabi median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 22% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1168.0; Rent percentile UAE-wide: 0.2155</small>
- **reach**: The nearest lounge, al-ain, is 19.0 km away in a straight line.
  <small>Distance to nearest lounge: 19.0153; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### muntazy-ajman — **GROW** (ai)

**GROW Muntazy: a new lounge would add about 12,000 net new women, out-serve 97% of UAE salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 12,165 women, take 183 from our lounges and add 11,982 net, 5,982 above the 6,000 line.
  <small>Net new women: 11982.107; New lounge would serve: 12165.0269; Taken from our lounges: 182.9199; Size gap: 5982</small>
- **demand**: That is more than a typical lounge would serve at 97% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 97th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9662; Demand gap: 0.4662; Demand percentile UAE-wide: 0.9662; New lounge would serve: 12165.0269</small>
- **cost**: Shop rent of AED 740/m² a year gives a rent ratio of 1.02 against the median Ajman salon site, 0.02 above the 1 line; dearer than 6% of UAE salon sites.
  <small>Rent ratio: 1.017; Rent gap: 0.017; Rent percentile UAE-wide: 0.0552; Shop rent in the area: 740.4</small>
- **reach**: The nearest lounge, al-jada, is 7.4 km away in a straight line.
  <small>Distance to nearest lounge: 7.3542; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### mazyad-abu-dhabi — **GROW** (ai)

**GROW Mazyad: a new lounge would add about 12,700 net new women, out-serve 99% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 12,714 women, take 3 from our lounges and add 12,712 net, 6,712 above the 6,000 line.
  <small>Net new women: 12711.6008; New lounge would serve: 12714.3273; Taken from our lounges: 2.7265; Size gap: 6712</small>
- **demand**: That is more than a typical lounge would serve at 99% of Abu Dhabi salon sites, 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9901; Demand gap: 0.4901; Demand percentile UAE-wide: 0.9777; New lounge would serve: 12714.3273</small>
- **cost**: Shop rent of AED 1,037/m² a year gives a rent ratio of 1.34 against the median Abu Dhabi salon site, 0.34 above the 1 line; dearer than 14% of UAE salon sites.
  <small>Rent ratio: 1.3443; Rent gap: 0.3443; Rent percentile UAE-wide: 0.1354; Shop rent in the area: 1037.0</small>
- **reach**: The nearest lounge, al-ain, is 27.9 km away in a straight line.
  <small>Distance to nearest lounge: 27.9167; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-khibeesi-abu-dhabi — **GROW** (ai)

**GROW Al Khibeesi: a new lounge would add about 7,000 net new women, out-serve 82% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 7,781 women, take 777 from our lounges and add 7,005 net, 1,005 above the 6,000 line.
  <small>Net new women: 7004.841; New lounge would serve: 7781.4159; Taken from our lounges: 776.5749; Size gap: 1005</small>
- **demand**: That is more than a typical lounge would serve at 82% of Abu Dhabi salon sites, 85th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8224; Demand gap: 0.3224; Demand percentile UAE-wide: 0.8495; New lounge would serve: 7781.4159</small>
- **cost**: Shop rent of AED 1,222/m² a year gives a rent ratio of 1.14 against the median Abu Dhabi salon site, 0.14 above the 1 line; dearer than 24% of UAE salon sites.
  <small>Rent ratio: 1.1408; Rent gap: 0.1408; Rent percentile UAE-wide: 0.2351; Shop rent in the area: 1222.0</small>
- **reach**: The nearest lounge, al-ain, is 3.9 km away in a straight line.
  <small>Distance to nearest lounge: 3.9347; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-rawdah-al-sharqiyah-abu-dhabi — **GROW** (ai)

**GROW Al Rawdah Al Sharqiyah: a new lounge would add about 8,200 net new women, out-serve 89% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 8,811 women, take 589 from our lounges and add 8,222 net, 2,222 above the 6,000 line.
  <small>Net new women: 8222.1747; New lounge would serve: 8811.2739; Taken from our lounges: 589.0991; Size gap: 2222</small>
- **demand**: That is more than a typical lounge would serve at 89% of Abu Dhabi salon sites, 90th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8882; Demand gap: 0.3882; Demand percentile UAE-wide: 0.8958; New lounge would serve: 8811.2739</small>
- **cost**: Shop rent of AED 1,034/m² a year gives a rent ratio of 1.35 against the median Abu Dhabi salon site, 0.35 above the 1 line; dearer than 14% of UAE salon sites.
  <small>Rent ratio: 1.3482; Rent gap: 0.3482; Rent percentile UAE-wide: 0.1354; Shop rent in the area: 1034.0</small>
- **reach**: The nearest lounge, al-ain, is 8.9 km away in a straight line.
  <small>Distance to nearest lounge: 8.8741; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### ghalilah-ras-al-khaimah — **GROW** (ai)

**GROW Ghalilah: a new lounge would add about 6,300 net new women and out-serve 79% of UAE salon sites; its rent is only the Ras Al Khaimah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 6,264 women and take almost none from our lounges, so 6,264 are net new, 264 above the 6,000 line.
  <small>Net new women: 6264.278; New lounge would serve: 6264.278; Taken from our lounges: 0.0; Size gap: 264</small>
- **demand**: That is more than a typical lounge would serve at 79% of UAE salon sites (Ras Al Khaimah has under 50, so ranked UAE-wide), 79th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.789; Demand gap: 0.289; Demand percentile UAE-wide: 0.789; New lounge would serve: 6264.278</small>
- **cost**: Shop rent of AED 819/m² a year is the Ras Al Khaimah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 7% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 818.7; Rent percentile UAE-wide: 0.0739</small>
- **reach**: The nearest lounge, ras-al-khaimah, is 27.7 km away in a straight line.
  <small>Distance to nearest lounge: 27.6637; Nearest lounge: ras-al-khaimah</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### dibba-al-hisn-sharjah — **GROW** (ai)

**GROW Dibba Al Hisn: a new lounge would add about 9,900 net new women and out-serve 82% of Sharjah salon sites; its rent is only the Sharjah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 9,898 women and take almost none from our lounges, so 9,898 are net new, 3,898 above the 6,000 line.
  <small>Net new women: 9897.8614; New lounge would serve: 9897.8614; Taken from our lounges: 0.0; Size gap: 3898</small>
- **demand**: That is more than a typical lounge would serve at 82% of Sharjah salon sites, 92nd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8182; Demand gap: 0.3182; Demand percentile UAE-wide: 0.9243; New lounge would serve: 9897.8614</small>
- **cost**: Shop rent of AED 1,121/m² a year is the Sharjah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 20% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1121.1; Rent percentile UAE-wide: 0.195</small>
- **reach**: The nearest lounge, ras-al-khaimah, is 37.9 km away: Dibba Al Hisn is white space for the network.
  <small>Distance to nearest lounge: 37.8936; Nearest lounge: ras-al-khaimah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### manama-ajman — **GROW** (ai)

**GROW Manama: a new lounge would add about 35,100 net new women and out-serve 100% of UAE salon sites; its rent is only the Ajman median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 35,094 women and take almost none from our lounges, so 35,094 are net new, 29,094 above the 6,000 line.
  <small>Net new women: 35094.2082; New lounge would serve: 35094.2082; Taken from our lounges: 0.0; Size gap: 29094</small>
- **demand**: That is more than a typical lounge would serve at 100% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 100th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9982; Demand gap: 0.4982; Demand percentile UAE-wide: 0.9982; New lounge would serve: 35094.2082</small>
- **cost**: Shop rent of AED 755/m² a year is the Ajman median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 7% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 755.0; Rent percentile UAE-wide: 0.073</small>
- **reach**: The nearest lounge, al-taif-mall, is 39.3 km away: Manama is white space for the network.
  <small>Distance to nearest lounge: 39.3036; Nearest lounge: al-taif-mall</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-shahamah-abu-dhabi — **GROW** (ai)

**GROW Al Shahamah: a new lounge would add about 6,300 net new women, out-serve 89% of Abu Dhabi salon sites and pay a rent no dearer than their median.**

- **size**: A new lounge would serve 8,887 women, take 2,607 from our lounges and add 6,280 net, 280 above the 6,000 line.
  <small>Net new women: 6279.7161; New lounge would serve: 8886.6863; Taken from our lounges: 2606.9702; Size gap: 280</small>
- **demand**: That is more than a typical lounge would serve at 89% of Abu Dhabi salon sites, 90th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8914; Demand gap: 0.3914; Demand percentile UAE-wide: 0.8985; New lounge would serve: 8886.6863</small>
- **cost**: Shop rent of AED 1,266/m² a year gives a rent ratio of 1.10 against the median Abu Dhabi salon site, 0.10 above the 1 line; dearer than 30% of UAE salon sites.
  <small>Rent ratio: 1.1011; Rent gap: 0.1011; Rent percentile UAE-wide: 0.3045; Shop rent in the area: 1266.0</small>
- **reach**: Our shahama lounge is only 1.3 km away in a straight line, so part of what a new site serves would come from it.
  <small>Distance to nearest lounge: 1.3018; Nearest lounge: shahama</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### khatt-ras-al-khaimah — **GROW** (ai)

**GROW Khatt: a new lounge would add about 8,100 net new women and out-serve 87% of UAE salon sites; its rent is only the Ras Al Khaimah median, so the rent test is neutral and the call low confidence.**

- **size**: A new lounge would serve 8,236 women, take 181 from our lounges and add 8,055 net, 2,055 above the 6,000 line.
  <small>Net new women: 8055.2107; New lounge would serve: 8236.0949; Taken from our lounges: 180.8842; Size gap: 2055</small>
- **demand**: That is more than a typical lounge would serve at 87% of UAE salon sites (Ras Al Khaimah has under 50, so ranked UAE-wide), 87th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8727; Demand gap: 0.3727; Demand percentile UAE-wide: 0.8727; New lounge would serve: 8236.0949</small>
- **cost**: Shop rent of AED 819/m² a year is the Ras Al Khaimah median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 7% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 818.7; Rent percentile UAE-wide: 0.0739</small>
- **reach**: The nearest lounge, ras-al-khaimah, is 14.9 km away in a straight line.
  <small>Distance to nearest lounge: 14.8786; Nearest lounge: ras-al-khaimah</small>
- **data_gap**: Our salon search covered only 25% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.2496; Coverage needed: 0.5; Coverage gap: -0.2504</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### mohamed-bin-zayed-city-abu-dhabi — **WATCH** (ai)

**WATCH Mohamed Bin Zayed City: a new lounge would add 3,749 net new women, 2,251 short of the 6,000 line.**

- **size**: A new lounge would serve 4,811 women, take 1,062 from our lounges and add 3,749 net, 2,251 short of the 6,000 line.
  <small>Net new women: 3749.1804; New lounge would serve: 4810.9931; Taken from our lounges: 1061.8127; Size gap: -2251</small>
- **demand**: That is more than a typical lounge would serve at 60% of Abu Dhabi salon sites, 71st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.5987; Demand gap: 0.0987; Demand percentile UAE-wide: 0.7115; New lounge would serve: 4810.9931</small>
- **cost**: Shop rent of AED 1,236/m² a year gives a rent ratio of 1.13 against the median Abu Dhabi salon site, 0.13 above the 1 line; dearer than 26% of UAE salon sites.
  <small>Rent ratio: 1.1278; Rent gap: 0.1278; Rent percentile UAE-wide: 0.26; Shop rent in the area: 1236.0</small>
- **reach**: The nearest lounge, mohammed-bin-zayed-city, is 3.8 km away in a straight line.
  <small>Distance to nearest lounge: 3.8105; Nearest lounge: mohammed-bin-zayed-city</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### muhaisnah-dubai — **WATCH** (ai)

**WATCH Muhaisnah: a new lounge would add 3,484 net new women, 2,516 short of the 6,000 line.**

- **size**: A new lounge would serve 3,595 women, take 111 from our lounges and add 3,484 net, 2,516 short of the 6,000 line.
  <small>Net new women: 3484.3553; New lounge would serve: 3595.2755; Taken from our lounges: 110.9202; Size gap: -2516</small>
- **demand**: That is more than a typical lounge would serve at 87% of Dubai salon sites, 61st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8677; Demand gap: 0.3677; Demand percentile UAE-wide: 0.6126; New lounge would serve: 3595.2755</small>
- **cost**: Shop rent of AED 1,957/m² a year gives a rent ratio of 1.10 against the median Dubai salon site, 0.10 above the 1 line; dearer than 58% of UAE salon sites.
  <small>Rent ratio: 1.1004; Rent gap: 0.1004; Rent percentile UAE-wide: 0.5815; Shop rent in the area: 1957.0</small>
- **reach**: The nearest lounge, mirdif-35, is 3.7 km away in a straight line.
  <small>Distance to nearest lounge: 3.7095; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-warqa-dubai — **WATCH** (ai)

**WATCH Al Warqa: a new lounge would add 4,625 net new women, 1,375 short of the 6,000 line.**

- **size**: A new lounge would serve 4,731 women, take 106 from our lounges and add 4,625 net, 1,375 short of the 6,000 line.
  <small>Net new women: 4625.1364; New lounge would serve: 4731.4735; Taken from our lounges: 106.3371; Size gap: -1375</small>
- **demand**: That is more than a typical lounge would serve at 97% of Dubai salon sites, 71st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9674; Demand gap: 0.4674; Demand percentile UAE-wide: 0.7088; New lounge would serve: 4731.4735</small>
- **cost**: Shop rent of AED 2,912/m² a year gives a rent ratio of 0.74 against the median Dubai salon site, 0.26 short of the 1 line; dearer than 91% of UAE salon sites.
  <small>Rent ratio: 0.7395; Rent gap: -0.2605; Rent percentile UAE-wide: 0.9065; Shop rent in the area: 2912.0</small>
- **reach**: The nearest lounge, mirdif-35, is 7.0 km away in a straight line.
  <small>Distance to nearest lounge: 6.9719; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-shamkhah-abu-dhabi — **WATCH** (ai)

**WATCH Al Shamkhah: a new lounge would add 5,989 net new women, 11 short of the 6,000 line.**

- **size**: A new lounge would serve 8,199 women, take 2,211 from our lounges and add 5,989 net, 11 short of the 6,000 line.
  <small>Net new women: 5988.5877; New lounge would serve: 8199.4217; Taken from our lounges: 2210.834; Size gap: -11</small>
- **demand**: That is more than a typical lounge would serve at 84% of Abu Dhabi salon sites, 87th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8421; Demand gap: 0.3421; Demand percentile UAE-wide: 0.8709; New lounge would serve: 8199.4217</small>
- **cost**: Shop rent of AED 2,630/m² a year gives a rent ratio of 0.53 against the median Abu Dhabi salon site, 0.47 short of the 1 line; dearer than 88% of UAE salon sites.
  <small>Rent ratio: 0.53; Rent gap: -0.47; Rent percentile UAE-wide: 0.8753; Shop rent in the area: 2630.0</small>
- **reach**: The nearest lounge, al-falah, is 7.1 km away in a straight line.
  <small>Distance to nearest lounge: 7.1413; Nearest lounge: al-falah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### wasit-sharjah — **WATCH** (ai)

**WATCH Wasit: a new lounge would add about 8,200 net new women, but its rent is dearer than the median Sharjah salon site.**

- **size**: A new lounge would serve 8,496 women, take 262 from our lounges and add 8,234 net, 2,234 above the 6,000 line.
  <small>Net new women: 8233.6413; New lounge would serve: 8495.6519; Taken from our lounges: 262.0107; Size gap: 2234</small>
- **demand**: That is more than a typical lounge would serve at 75% of Sharjah salon sites, 88th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7483; Demand gap: 0.2483; Demand percentile UAE-wide: 0.8816; New lounge would serve: 8495.6519</small>
- **cost**: Shop rent of AED 1,685/m² a year gives a rent ratio of 0.67 against the median Sharjah salon site, 0.33 short of the 1 line; dearer than 51% of UAE salon sites.
  <small>Rent ratio: 0.6653; Rent gap: -0.3347; Rent percentile UAE-wide: 0.5111; Shop rent in the area: 1685.1</small>
- **reach**: The nearest lounge, zawaya-walk, is 4.0 km away in a straight line.
  <small>Distance to nearest lounge: 4.0139; Nearest lounge: zawaya-walk</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-wathbah-abu-dhabi — **WATCH** (ai)

**WATCH Al Wathbah: a new lounge would add about 7,500 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 9,987 women, take 2,442 from our lounges and add 7,545 net, 1,545 above the 6,000 line.
  <small>Net new women: 7545.0491; New lounge would serve: 9987.4433; Taken from our lounges: 2442.3943; Size gap: 1545</small>
- **demand**: That is more than a typical lounge would serve at 94% of Abu Dhabi salon sites, 93rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9408; Demand gap: 0.4408; Demand percentile UAE-wide: 0.9279; New lounge would serve: 9987.4433</small>
- **cost**: Shop rent of AED 2,312/m² a year gives a rent ratio of 0.60 against the median Abu Dhabi salon site, 0.40 short of the 1 line; dearer than 81% of UAE salon sites.
  <small>Rent ratio: 0.6029; Rent gap: -0.3971; Rent percentile UAE-wide: 0.8121; Shop rent in the area: 2312.0</small>
- **reach**: The nearest lounge, baniyas, is 9.4 km away in a straight line.
  <small>Distance to nearest lounge: 9.388; Nearest lounge: baniyas</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### dubai-investment-park-1-dubai — **WATCH** (ai)

**WATCH Dubai Investment Park 1: a new lounge would add 4,625 net new women, 1,375 short of the 6,000 line.**

- **size**: A new lounge would serve 4,652 women, take 27 from our lounges and add 4,625 net, 1,375 short of the 6,000 line.
  <small>Net new women: 4624.6263; New lounge would serve: 4651.7933; Taken from our lounges: 27.167; Size gap: -1375</small>
- **demand**: That is more than a typical lounge would serve at 96% of Dubai salon sites, 70th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9639; Demand gap: 0.4639; Demand percentile UAE-wide: 0.7035; New lounge would serve: 4651.7933</small>
- **cost**: Shop rent of AED 1,436/m² a year gives a rent ratio of 1.50 against the median Dubai salon site, 0.50 above the 1 line; dearer than 38% of UAE salon sites.
  <small>Rent ratio: 1.4997; Rent gap: 0.4997; Rent percentile UAE-wide: 0.3793; Shop rent in the area: 1436.0</small>
- **reach**: The nearest lounge, jumeirah-park, is 5.7 km away in a straight line.
  <small>Distance to nearest lounge: 5.7138; Nearest lounge: jumeirah-park</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-lesaily-dubai — **WATCH** (ai)

**WATCH Al Lesaily: a new lounge would add 5,625 net new women, 375 short of the 6,000 line.**

- **size**: A new lounge would serve 5,626 women and take almost none from our lounges, so 5,625 are net new, 375 short of the 6,000 line.
  <small>Net new women: 5625.2643; New lounge would serve: 5625.7071; Taken from our lounges: 0.4429; Size gap: -375</small>
- **demand**: That is more than a typical lounge would serve at 98% of Dubai salon sites, 76th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9845; Demand gap: 0.4845; Demand percentile UAE-wide: 0.7587; New lounge would serve: 5625.7071</small>
- **cost**: Shop rent of AED 1,985/m² a year is the Dubai median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 60% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1985.0; Rent percentile UAE-wide: 0.5975</small>
- **reach**: The nearest lounge, nad-al-sheba, is 27.1 km away in a straight line.
  <small>Distance to nearest lounge: 27.0827; Nearest lounge: nad-al-sheba</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-bateen-abu-dhabi — **WATCH** (ai)

**WATCH Al Bateen: a new lounge would add 4,296 net new women, 1,704 short of the 6,000 line.**

- **size**: A new lounge would serve 5,688 women, take 1,392 from our lounges and add 4,296 net, 1,704 short of the 6,000 line.
  <small>Net new women: 4295.6935; New lounge would serve: 5687.5086; Taken from our lounges: 1391.8151; Size gap: -1704</small>
- **demand**: That is more than a typical lounge would serve at 67% of Abu Dhabi salon sites, 76th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.6743; Demand gap: 0.1743; Demand percentile UAE-wide: 0.7596; New lounge would serve: 5687.5086</small>
- **cost**: Shop rent of AED 1,380/m² a year gives a rent ratio of 1.01 against the median Abu Dhabi salon site, 0.01 above the 1 line; dearer than 34% of UAE salon sites.
  <small>Rent ratio: 1.0101; Rent gap: 0.0101; Rent percentile UAE-wide: 0.3411; Shop rent in the area: 1380.0</small>
- **reach**: The nearest lounge, al-falah, is 9.2 km away in a straight line.
  <small>Distance to nearest lounge: 9.1519; Nearest lounge: al-falah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-bahyah-abu-dhabi — **WATCH** (ai)

**WATCH Al Bahyah: a new lounge would add 4,692 net new women, 1,308 short of the 6,000 line.**

- **size**: A new lounge would serve 6,639 women, take 1,947 from our lounges and add 4,692 net, 1,308 short of the 6,000 line.
  <small>Net new women: 4692.2626; New lounge would serve: 6639.4611; Taken from our lounges: 1947.1985; Size gap: -1308</small>
- **demand**: That is more than a typical lounge would serve at 76% of Abu Dhabi salon sites, 80th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7632; Demand gap: 0.2632; Demand percentile UAE-wide: 0.7996; New lounge would serve: 6639.4611</small>
- **cost**: Shop rent of AED 1,747/m² a year gives a rent ratio of 0.80 against the median Abu Dhabi salon site, 0.20 short of the 1 line; dearer than 54% of UAE salon sites.
  <small>Rent ratio: 0.7979; Rent gap: -0.2021; Rent percentile UAE-wide: 0.5396; Shop rent in the area: 1747.0</small>
- **reach**: Our shahama lounge is only 2.5 km away in a straight line, so part of what a new site serves would come from it.
  <small>Distance to nearest lounge: 2.4816; Nearest lounge: shahama</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### warsan-dubai — **WATCH** (ai)

**WATCH Warsan: a new lounge would add 3,260 net new women, 2,740 short of the 6,000 line.**

- **size**: A new lounge would serve 3,330 women, take 69 from our lounges and add 3,260 net, 2,740 short of the 6,000 line.
  <small>Net new women: 3260.4728; New lounge would serve: 3329.8473; Taken from our lounges: 69.3745; Size gap: -2740</small>
- **demand**: That is more than a typical lounge would serve at 82% of Dubai salon sites, 57th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8162; Demand gap: 0.3162; Demand percentile UAE-wide: 0.5744; New lounge would serve: 3329.8473</small>
- **cost**: Shop rent of AED 1,011/m² a year gives a rent ratio of 2.13 against the median Dubai salon site, 1.13 above the 1 line; dearer than 12% of UAE salon sites.
  <small>Rent ratio: 2.1301; Rent gap: 1.1301; Rent percentile UAE-wide: 0.1229; Shop rent in the area: 1011.0</small>
- **reach**: The nearest lounge, nad-al-sheba, is 6.7 km away in a straight line.
  <small>Distance to nearest lounge: 6.6536; Nearest lounge: nad-al-sheba</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-falah-abu-dhabi — **WATCH** (ai)

**WATCH Al Falah: a new lounge would add 4,847 net new women, 1,153 short of the 6,000 line.**

- **size**: A new lounge would serve 6,974 women, take 2,126 from our lounges and add 4,847 net, 1,153 short of the 6,000 line.
  <small>Net new women: 4847.0611; New lounge would serve: 6973.5426; Taken from our lounges: 2126.4816; Size gap: -1153</small>
- **demand**: That is more than a typical lounge would serve at 78% of Abu Dhabi salon sites, 81st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7829; Demand gap: 0.2829; Demand percentile UAE-wide: 0.813; New lounge would serve: 6973.5426</small>
- **cost**: Shop rent of AED 1,502/m² a year gives a rent ratio of 0.93 against the median Abu Dhabi salon site, 0.07 short of the 1 line; dearer than 40% of UAE salon sites.
  <small>Rent ratio: 0.9281; Rent gap: -0.0719; Rent percentile UAE-wide: 0.3989; Shop rent in the area: 1502.0</small>
- **reach**: Our al-falah lounge is only 1.6 km away in a straight line, so part of what a new site serves would come from it.
  <small>Distance to nearest lounge: 1.6145; Nearest lounge: al-falah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-samhah-abu-dhabi — **WATCH** (ai)

**WATCH Al Samhah: a new lounge would add about 10,500 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 12,314 women, take 1,817 from our lounges and add 10,497 net, 4,497 above the 6,000 line.
  <small>Net new women: 10496.9687; New lounge would serve: 12313.9934; Taken from our lounges: 1817.0247; Size gap: 4497</small>
- **demand**: That is more than a typical lounge would serve at 99% of Abu Dhabi salon sites, 97th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9901; Demand gap: 0.4901; Demand percentile UAE-wide: 0.9688; New lounge would serve: 12313.9934</small>
- **cost**: Shop rent of AED 2,059/m² a year gives a rent ratio of 0.68 against the median Abu Dhabi salon site, 0.32 short of the 1 line; dearer than 65% of UAE salon sites.
  <small>Rent ratio: 0.677; Rent gap: -0.323; Rent percentile UAE-wide: 0.6483; Shop rent in the area: 2059.0</small>
- **reach**: The nearest lounge, shahama, is 17.6 km away in a straight line.
  <small>Distance to nearest lounge: 17.6398; Nearest lounge: shahama</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### jarn-yafour-abu-dhabi — **WATCH** (ai)

**WATCH Jarn Yafour: a new lounge would add 5,363 net new women, 637 short of the 6,000 line.**

- **size**: A new lounge would serve 7,053 women, take 1,690 from our lounges and add 5,363 net, 637 short of the 6,000 line.
  <small>Net new women: 5363.3236; New lounge would serve: 7052.932; Taken from our lounges: 1689.6084; Size gap: -637</small>
- **demand**: That is more than a typical lounge would serve at 79% of Abu Dhabi salon sites, 82nd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7895; Demand gap: 0.2895; Demand percentile UAE-wide: 0.8183; New lounge would serve: 7052.932</small>
- **cost**: Shop rent of AED 619/m² a year gives a rent ratio of 2.25 against the median Abu Dhabi salon site, 1.25 above the 1 line; dearer than 2% of UAE salon sites.
  <small>Rent ratio: 2.252; Rent gap: 1.252; Rent percentile UAE-wide: 0.0214; Shop rent in the area: 619.0</small>
- **reach**: The nearest lounge, baniyas, is 4.0 km away in a straight line.
  <small>Distance to nearest lounge: 4.0469; Nearest lounge: baniyas</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### oud-al-muteena-dubai — **WATCH** (ai)

**WATCH Oud Al Muteena: a new lounge would add 3,451 net new women, 2,549 short of the 6,000 line.**

- **size**: A new lounge would serve 3,559 women, take 108 from our lounges and add 3,451 net, 2,549 short of the 6,000 line.
  <small>Net new women: 3450.56; New lounge would serve: 3558.8497; Taken from our lounges: 108.2897; Size gap: -2549</small>
- **demand**: That is more than a typical lounge would serve at 86% of Dubai salon sites, 61st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8625; Demand gap: 0.3625; Demand percentile UAE-wide: 0.6073; New lounge would serve: 3558.8497</small>
- **cost**: Shop rent of AED 2,885/m² a year gives a rent ratio of 0.75 against the median Dubai salon site, 0.25 short of the 1 line; dearer than 91% of UAE salon sites.
  <small>Rent ratio: 0.7464; Rent gap: -0.2536; Rent percentile UAE-wide: 0.9056; Shop rent in the area: 2885.0</small>
- **reach**: The nearest lounge, mirdif-35, is 3.9 km away in a straight line.
  <small>Distance to nearest lounge: 3.8888; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### shakhbout-city-abu-dhabi — **WATCH** (ai)

**WATCH Shakhbout City: a new lounge would add 5,482 net new women, 518 short of the 6,000 line.**

- **size**: A new lounge would serve 7,371 women, take 1,889 from our lounges and add 5,482 net, 518 short of the 6,000 line.
  <small>Net new women: 5482.278; New lounge would serve: 7371.1601; Taken from our lounges: 1888.8821; Size gap: -518</small>
- **demand**: That is more than a typical lounge would serve at 80% of Abu Dhabi salon sites, 83rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7993; Demand gap: 0.2993; Demand percentile UAE-wide: 0.8299; New lounge would serve: 7371.1601</small>
- **cost**: Shop rent of AED 1,815/m² a year gives a rent ratio of 0.77 against the median Abu Dhabi salon site, 0.23 short of the 1 line; dearer than 56% of UAE salon sites.
  <small>Rent ratio: 0.768; Rent gap: -0.232; Rent percentile UAE-wide: 0.5592; Shop rent in the area: 1815.0</small>
- **reach**: Our shakhbout-city lounge is only 0.8 km away in a straight line, so part of what a new site serves would come from it.
  <small>Distance to nearest lounge: 0.8315; Nearest lounge: shakhbout-city</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-mizhar-dubai — **WATCH** (ai)

**WATCH Al Mizhar: a new lounge would add 4,261 net new women, 1,739 short of the 6,000 line.**

- **size**: A new lounge would serve 4,397 women, take 135 from our lounges and add 4,261 net, 1,739 short of the 6,000 line.
  <small>Net new women: 4261.3348; New lounge would serve: 4396.678; Taken from our lounges: 135.3432; Size gap: -1739</small>
- **demand**: That is more than a typical lounge would serve at 95% of Dubai salon sites, 68th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9536; Demand gap: 0.4536; Demand percentile UAE-wide: 0.683; New lounge would serve: 4396.678</small>
- **cost**: Shop rent of AED 2,394/m² a year gives a rent ratio of 0.90 against the median Dubai salon site, 0.10 short of the 1 line; dearer than 84% of UAE salon sites.
  <small>Rent ratio: 0.8995; Rent gap: -0.1005; Rent percentile UAE-wide: 0.8442; Shop rent in the area: 2394.0</small>
- **reach**: Our mirdif-35 lounge is only 0.9 km away in a straight line, yet a new site would take just 135 women from our lounges.
  <small>Distance to nearest lounge: 0.9359; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-aamerah-abu-dhabi — **WATCH** (ai)

**WATCH Al Aamerah: a new lounge would add about 6,700 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 7,640 women, take 954 from our lounges and add 6,686 net, 686 above the 6,000 line.
  <small>Net new women: 6686.1397; New lounge would serve: 7639.7887; Taken from our lounges: 953.649; Size gap: 686</small>
- **demand**: That is more than a typical lounge would serve at 81% of Abu Dhabi salon sites, 84th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8092; Demand gap: 0.3092; Demand percentile UAE-wide: 0.8379; New lounge would serve: 7639.7887</small>
- **cost**: Shop rent of AED 1,785/m² a year gives a rent ratio of 0.78 against the median Abu Dhabi salon site, 0.22 short of the 1 line; dearer than 56% of UAE salon sites.
  <small>Rent ratio: 0.781; Rent gap: -0.219; Rent percentile UAE-wide: 0.5574; Shop rent in the area: 1785.0</small>
- **reach**: The nearest lounge, al-ain, is 11.2 km away in a straight line.
  <small>Distance to nearest lounge: 11.2473; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### wadi-al-amardi-dubai — **WATCH** (ai)

**WATCH Wadi Al Amardi: a new lounge would add 4,225 net new women, 1,775 short of the 6,000 line.**

- **size**: A new lounge would serve 4,350 women, take 126 from our lounges and add 4,225 net, 1,775 short of the 6,000 line.
  <small>Net new women: 4224.5097; New lounge would serve: 4350.2143; Taken from our lounges: 125.7046; Size gap: -1775</small>
- **demand**: That is more than a typical lounge would serve at 95% of Dubai salon sites, 68th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9519; Demand gap: 0.4519; Demand percentile UAE-wide: 0.6803; New lounge would serve: 4350.2143</small>
- **cost**: Shop rent of AED 2,351/m² a year gives a rent ratio of 0.92 against the median Dubai salon site, 0.08 short of the 1 line; dearer than 81% of UAE salon sites.
  <small>Rent ratio: 0.916; Rent gap: -0.084; Rent percentile UAE-wide: 0.8148; Shop rent in the area: 2351.0</small>
- **reach**: The nearest lounge, mirdif-35, is 5.8 km away in a straight line.
  <small>Distance to nearest lounge: 5.8064; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### ghiyathi-abu-dhabi — **WATCH** (ai)

**WATCH Ghiyathi: a new lounge would add 3,739 net new women, 2,261 short of the 6,000 line.**

- **size**: A new lounge would serve 3,739 women and take almost none from our lounges, so 3,739 are net new, 2,261 short of the 6,000 line.
  <small>Net new women: 3739.2979; New lounge would serve: 3739.2979; Taken from our lounges: 0.0; Size gap: -2261</small>
- **demand**: That is more than a typical lounge would serve at 47% of Abu Dhabi salon sites, 63rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.4737; Demand gap: -0.0263; Demand percentile UAE-wide: 0.6287; New lounge would serve: 3739.2979</small>
- **cost**: Shop rent of AED 1,260/m² a year gives a rent ratio of 1.11 against the median Abu Dhabi salon site, 0.11 above the 1 line; dearer than 30% of UAE salon sites.
  <small>Rent ratio: 1.1063; Rent gap: 0.1063; Rent percentile UAE-wide: 0.2956; Shop rent in the area: 1260.0</small>
- **reach**: The nearest lounge, al-dhafra, is 98.7 km away: Ghiyathi is white space for the network.
  <small>Distance to nearest lounge: 98.7292; Nearest lounge: al-dhafra</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-jimi-abu-dhabi — **WATCH** (ai)

**WATCH Al Jimi: a new lounge would add 5,473 net new women, 527 short of the 6,000 line.**

- **size**: A new lounge would serve 5,912 women, take 439 from our lounges and add 5,473 net, 527 short of the 6,000 line.
  <small>Net new women: 5473.3425; New lounge would serve: 5912.0345; Taken from our lounges: 438.692; Size gap: -527</small>
- **demand**: That is more than a typical lounge would serve at 71% of Abu Dhabi salon sites, 77th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7138; Demand gap: 0.2138; Demand percentile UAE-wide: 0.7738; New lounge would serve: 5912.0345</small>
- **cost**: Shop rent of AED 995/m² a year gives a rent ratio of 1.40 against the median Abu Dhabi salon site, 0.40 above the 1 line; dearer than 10% of UAE salon sites.
  <small>Rent ratio: 1.401; Rent gap: 0.401; Rent percentile UAE-wide: 0.1042; Shop rent in the area: 995.0</small>
- **reach**: The nearest lounge, al-ain, is 8.2 km away in a straight line.
  <small>Distance to nearest lounge: 8.2461; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### bani-yas-abu-dhabi — **WATCH** (ai)

**WATCH Bani Yas: a new lounge would add about 8,300 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 11,249 women, take 2,944 from our lounges and add 8,305 net, 2,305 above the 6,000 line.
  <small>Net new women: 8304.6311; New lounge would serve: 11249.1173; Taken from our lounges: 2944.4863; Size gap: 2305</small>
- **demand**: That is more than a typical lounge would serve at 98% of Abu Dhabi salon sites, 95th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.977; Demand gap: 0.477; Demand percentile UAE-wide: 0.951; New lounge would serve: 11249.1173</small>
- **cost**: Shop rent of AED 2,003/m² a year gives a rent ratio of 0.70 against the median Abu Dhabi salon site, 0.30 short of the 1 line; dearer than 62% of UAE salon sites.
  <small>Rent ratio: 0.696; Rent gap: -0.304; Rent percentile UAE-wide: 0.6198; Shop rent in the area: 2003.0</small>
- **reach**: Our baniyas lounge is only 1.0 km away in a straight line, so part of what a new site serves would come from it.
  <small>Distance to nearest lounge: 0.9589; Nearest lounge: baniyas</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-dhait-south-ras-al-khaimah — **WATCH** (ai)

**WATCH Al Dhait South: a new lounge would add about 6,100 net new women, but its rent is dearer than the median Ras Al Khaimah salon site.**

- **size**: A new lounge would serve 6,742 women, take 617 from our lounges and add 6,126 net, 126 above the 6,000 line.
  <small>Net new women: 6125.5811; New lounge would serve: 6742.3638; Taken from our lounges: 616.7827; Size gap: 126</small>
- **demand**: That is more than a typical lounge would serve at 80% of UAE salon sites (Ras Al Khaimah has under 50, so ranked UAE-wide), 80th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8041; Demand gap: 0.3041; Demand percentile UAE-wide: 0.8041; New lounge would serve: 6742.3638</small>
- **cost**: Shop rent of AED 1,033/m² a year gives a rent ratio of 0.83 against the median Ras Al Khaimah salon site, 0.17 short of the 1 line; dearer than 13% of UAE salon sites.
  <small>Rent ratio: 0.8255; Rent gap: -0.1745; Rent percentile UAE-wide: 0.13; Shop rent in the area: 1032.8</small>
- **reach**: Our ras-al-khaimah lounge is only 2.6 km away in a straight line, so part of what a new site serves would come from it.
  <small>Distance to nearest lounge: 2.565; Nearest lounge: ras-al-khaimah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### mirdif-dubai — **WATCH** (ai)

**WATCH Mirdif: a new lounge would add 3,697 net new women, 2,303 short of the 6,000 line.**

- **size**: A new lounge would serve 3,796 women, take 99 from our lounges and add 3,697 net, 2,303 short of the 6,000 line.
  <small>Net new women: 3697.4626; New lounge would serve: 3796.3263; Taken from our lounges: 98.8637; Size gap: -2303</small>
- **demand**: That is more than a typical lounge would serve at 91% of Dubai salon sites, 64th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9089; Demand gap: 0.4089; Demand percentile UAE-wide: 0.6376; New lounge would serve: 3796.3263</small>
- **cost**: Shop rent of AED 2,246/m² a year gives a rent ratio of 0.96 against the median Dubai salon site, 0.04 short of the 1 line; dearer than 75% of UAE salon sites.
  <small>Rent ratio: 0.9588; Rent gap: -0.0412; Rent percentile UAE-wide: 0.7524; Shop rent in the area: 2246.0</small>
- **reach**: Our mirdif-35 lounge is only 2.0 km away in a straight line, yet a new site would take just 99 women from our lounges.
  <small>Distance to nearest lounge: 2.0424; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-khawaneej-1-dubai — **WATCH** (ai)

**WATCH Al Khawaneej 1: a new lounge would add 3,896 net new women, 2,104 short of the 6,000 line.**

- **size**: A new lounge would serve 4,009 women, take 113 from our lounges and add 3,896 net, 2,104 short of the 6,000 line.
  <small>Net new women: 3895.6947; New lounge would serve: 4008.5622; Taken from our lounges: 112.8675; Size gap: -2104</small>
- **demand**: That is more than a typical lounge would serve at 93% of Dubai salon sites, 66th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9296; Demand gap: 0.4296; Demand percentile UAE-wide: 0.6581; New lounge would serve: 4008.5622</small>
- **cost**: Shop rent of AED 3,502/m² a year gives a rent ratio of 0.61 against the median Dubai salon site, 0.39 short of the 1 line; dearer than 95% of UAE salon sites.
  <small>Rent ratio: 0.6149; Rent gap: -0.3851; Rent percentile UAE-wide: 0.9475; Shop rent in the area: 3502.0</small>
- **reach**: The nearest lounge, mirdif-35, is 5.9 km away in a straight line.
  <small>Distance to nearest lounge: 5.8549; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-dhahir-abu-dhabi — **WATCH** (ai)

**WATCH Al Dhahir: a new lounge would add about 15,900 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 15,988 women, take 56 from our lounges and add 15,932 net, 9,932 above the 6,000 line.
  <small>Net new women: 15932.1928; New lounge would serve: 15987.7119; Taken from our lounges: 55.5191; Size gap: 9932</small>
- **demand**: That is more than a typical lounge would serve at 100% of Abu Dhabi salon sites, 98th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9967; Demand gap: 0.4967; Demand percentile UAE-wide: 0.9849; New lounge would serve: 15987.7119</small>
- **cost**: Shop rent of AED 1,891/m² a year gives a rent ratio of 0.74 against the median Abu Dhabi salon site, 0.26 short of the 1 line; dearer than 58% of UAE salon sites.
  <small>Rent ratio: 0.7372; Rent gap: -0.2628; Rent percentile UAE-wide: 0.5779; Shop rent in the area: 1891.0</small>
- **reach**: The nearest lounge, al-ain, is 24.7 km away in a straight line.
  <small>Distance to nearest lounge: 24.7016; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### hili-abu-dhabi — **WATCH** (ai)

**WATCH Hili: a new lounge would add 5,585 net new women, 415 short of the 6,000 line.**

- **size**: A new lounge would serve 5,892 women, take 307 from our lounges and add 5,585 net, 415 short of the 6,000 line.
  <small>Net new women: 5585.2038; New lounge would serve: 5892.1497; Taken from our lounges: 306.9458; Size gap: -415</small>
- **demand**: That is more than a typical lounge would serve at 71% of Abu Dhabi salon sites, 77th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7105; Demand gap: 0.2105; Demand percentile UAE-wide: 0.7711; New lounge would serve: 5892.1497</small>
- **cost**: Shop rent of AED 1,206/m² a year gives a rent ratio of 1.16 against the median Abu Dhabi salon site, 0.16 above the 1 line; dearer than 23% of UAE salon sites.
  <small>Rent ratio: 1.1559; Rent gap: 0.1559; Rent percentile UAE-wide: 0.2342; Shop rent in the area: 1206.0</small>
- **reach**: The nearest lounge, al-ain, is 14.4 km away in a straight line.
  <small>Distance to nearest lounge: 14.4047; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### rabdan-abu-dhabi — **WATCH** (ai)

**WATCH Rabdan: a new lounge would add 3,662 net new women, 2,338 short of the 6,000 line.**

- **size**: A new lounge would serve 4,667 women, take 1,005 from our lounges and add 3,662 net, 2,338 short of the 6,000 line.
  <small>Net new women: 3661.7327; New lounge would serve: 4666.6351; Taken from our lounges: 1004.9025; Size gap: -2338</small>
- **demand**: That is more than a typical lounge would serve at 59% of Abu Dhabi salon sites, 71st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.5921; Demand gap: 0.0921; Demand percentile UAE-wide: 0.7061; New lounge would serve: 4666.6351</small>
- **cost**: Shop rent of AED 1,348/m² a year gives a rent ratio of 1.03 against the median Abu Dhabi salon site, 0.03 above the 1 line; dearer than 33% of UAE salon sites.
  <small>Rent ratio: 1.0341; Rent gap: 0.0341; Rent percentile UAE-wide: 0.333; Shop rent in the area: 1348.0</small>
- **reach**: Our al-maqta lounge is only 1.3 km away in a straight line, so part of what a new site serves would come from it.
  <small>Distance to nearest lounge: 1.344; Nearest lounge: al-maqta</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-khawaneej-2-dubai — **WATCH** (ai)

**WATCH Al Khawaneej 2: a new lounge would add 5,775 net new women, 225 short of the 6,000 line.**

- **size**: A new lounge would serve 5,918 women, take 143 from our lounges and add 5,775 net, 225 short of the 6,000 line.
  <small>Net new women: 5774.8396; New lounge would serve: 5918.132; Taken from our lounges: 143.2925; Size gap: -225</small>
- **demand**: That is more than a typical lounge would serve at 99% of Dubai salon sites, 77th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9863; Demand gap: 0.4863; Demand percentile UAE-wide: 0.7738; New lounge would serve: 5918.132</small>
- **cost**: Shop rent of AED 2,722/m² a year gives a rent ratio of 0.79 against the median Dubai salon site, 0.21 short of the 1 line; dearer than 89% of UAE salon sites.
  <small>Rent ratio: 0.7911; Rent gap: -0.2089; Rent percentile UAE-wide: 0.894; Shop rent in the area: 2722.0</small>
- **reach**: The nearest lounge, mirdif-35, is 8.7 km away in a straight line.
  <small>Distance to nearest lounge: 8.699; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-muwaij-i-abu-dhabi — **WATCH** (ai)

**WATCH Al Muwaij'i: a new lounge would add about 7,400 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 8,057 women, take 687 from our lounges and add 7,370 net, 1,370 above the 6,000 line.
  <small>Net new women: 7369.8858; New lounge would serve: 8056.877; Taken from our lounges: 686.9912; Size gap: 1370</small>
- **demand**: That is more than a typical lounge would serve at 83% of Abu Dhabi salon sites, 86th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8289; Demand gap: 0.3289; Demand percentile UAE-wide: 0.8611; New lounge would serve: 8056.877</small>
- **cost**: Shop rent of AED 2,142/m² a year gives a rent ratio of 0.65 against the median Abu Dhabi salon site, 0.35 short of the 1 line; dearer than 68% of UAE salon sites.
  <small>Rent ratio: 0.6508; Rent gap: -0.3492; Rent percentile UAE-wide: 0.6821; Shop rent in the area: 2142.0</small>
- **reach**: The nearest lounge, al-ain, is 5.9 km away in a straight line.
  <small>Distance to nearest lounge: 5.8522; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-fou-ah-abu-dhabi — **WATCH** (ai)

**WATCH Al Fou'ah: a new lounge would add 5,976 net new women, 24 short of the 6,000 line.**

- **size**: A new lounge would serve 6,217 women, take 241 from our lounges and add 5,976 net, 24 short of the 6,000 line.
  <small>Net new women: 5975.801; New lounge would serve: 6216.7811; Taken from our lounges: 240.9802; Size gap: -24</small>
- **demand**: That is more than a typical lounge would serve at 74% of Abu Dhabi salon sites, 79th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7401; Demand gap: 0.2401; Demand percentile UAE-wide: 0.7872; New lounge would serve: 6216.7811</small>
- **cost**: Shop rent of AED 731/m² a year gives a rent ratio of 1.91 against the median Abu Dhabi salon site, 0.91 above the 1 line; dearer than 5% of UAE salon sites.
  <small>Rent ratio: 1.907; Rent gap: 0.907; Rent percentile UAE-wide: 0.0525; Shop rent in the area: 731.0</small>
- **reach**: The nearest lounge, al-ain, is 19.9 km away in a straight line.
  <small>Distance to nearest lounge: 19.9361; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-sader-abu-dhabi — **WATCH** (ai)

**WATCH Al Sader: a new lounge would add about 7,000 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 8,788 women, take 1,801 from our lounges and add 6,987 net, 987 above the 6,000 line.
  <small>Net new women: 6987.2024; New lounge would serve: 8787.8328; Taken from our lounges: 1800.6304; Size gap: 987</small>
- **demand**: That is more than a typical lounge would serve at 88% of Abu Dhabi salon sites, 89th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8849; Demand gap: 0.3849; Demand percentile UAE-wide: 0.8949; New lounge would serve: 8787.8328</small>
- **cost**: Shop rent of AED 1,464/m² a year gives a rent ratio of 0.95 against the median Abu Dhabi salon site, 0.05 short of the 1 line; dearer than 38% of UAE salon sites.
  <small>Rent ratio: 0.9522; Rent gap: -0.0478; Rent percentile UAE-wide: 0.3847; Shop rent in the area: 1464.0</small>
- **reach**: The nearest lounge, shahama, is 13.4 km away in a straight line.
  <small>Distance to nearest lounge: 13.412; Nearest lounge: shahama</small>
- **data_gap**: Our salon search covered only 41% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.4071; Coverage needed: 0.5; Coverage gap: -0.0929</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### habshan-abu-dhabi — **WATCH** (ai)

**WATCH Habshan: a new lounge would add 3,358 net new women, 2,642 short of the 6,000 line.**

- **size**: A new lounge would serve 3,358 women and take almost none from our lounges, so 3,358 are net new, 2,642 short of the 6,000 line.
  <small>Net new women: 3357.5587; New lounge would serve: 3357.5587; Taken from our lounges: 0.0; Size gap: -2642</small>
- **demand**: That is more than a typical lounge would serve at 46% of Abu Dhabi salon sites, 58th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.4572; Demand gap: -0.0428; Demand percentile UAE-wide: 0.5788; New lounge would serve: 3357.5587</small>
- **cost**: Shop rent of AED 1,396/m² a year gives a rent ratio of 0.999 against the median Abu Dhabi salon site, 0.001 short of the 1 line; dearer than 37% of UAE salon sites.
  <small>Rent ratio: 0.9986; Rent gap: -0.0014; Rent percentile UAE-wide: 0.3722; Shop rent in the area: 1396.0</small>
- **reach**: The nearest lounge, al-dhafra, is 22.6 km away in a straight line.
  <small>Distance to nearest lounge: 22.6397; Nearest lounge: al-dhafra</small>
- **data_gap**: Our salon search covered only 2% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0226; Coverage needed: 0.5; Coverage gap: -0.4774</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-shawamekh-abu-dhabi — **WATCH** (ai)

**WATCH Al Shawamekh: a new lounge would add 4,375 net new women, 1,625 short of the 6,000 line.**

- **size**: A new lounge would serve 5,868 women, take 1,492 from our lounges and add 4,375 net, 1,625 short of the 6,000 line.
  <small>Net new women: 4375.2036; New lounge would serve: 5867.5529; Taken from our lounges: 1492.3493; Size gap: -1625</small>
- **demand**: That is more than a typical lounge would serve at 71% of Abu Dhabi salon sites, 77th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7105; Demand gap: 0.2105; Demand percentile UAE-wide: 0.7711; New lounge would serve: 5867.5529</small>
- **cost**: Shop rent of AED 1,989/m² a year gives a rent ratio of 0.70 against the median Abu Dhabi salon site, 0.30 short of the 1 line; dearer than 62% of UAE salon sites.
  <small>Rent ratio: 0.7009; Rent gap: -0.2991; Rent percentile UAE-wide: 0.618; Shop rent in the area: 1989.0</small>
- **reach**: The nearest lounge, shakhbout-city, is 3.6 km away in a straight line.
  <small>Distance to nearest lounge: 3.6303; Nearest lounge: shakhbout-city</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-tiwayya-abu-dhabi — **WATCH** (ai)

**WATCH Al Tiwayya: a new lounge would add 5,827 net new women, 173 short of the 6,000 line.**

- **size**: A new lounge would serve 6,442 women, take 615 from our lounges and add 5,827 net, 173 short of the 6,000 line.
  <small>Net new women: 5827.235; New lounge would serve: 6441.8582; Taken from our lounges: 614.6232; Size gap: -173</small>
- **demand**: That is more than a typical lounge would serve at 75% of Abu Dhabi salon sites, 79th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.75; Demand gap: 0.25; Demand percentile UAE-wide: 0.7916; New lounge would serve: 6441.8582</small>
- **cost**: Shop rent of AED 1,860/m² a year gives a rent ratio of 0.75 against the median Abu Dhabi salon site, 0.25 short of the 1 line; dearer than 56% of UAE salon sites.
  <small>Rent ratio: 0.7495; Rent gap: -0.2505; Rent percentile UAE-wide: 0.5637; Shop rent in the area: 1860.0</small>
- **reach**: The nearest lounge, al-ain, is 4.6 km away in a straight line.
  <small>Distance to nearest lounge: 4.5709; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-nahdah-abu-dhabi — **WATCH** (ai)

**WATCH Al Nahdah: a new lounge would add about 6,100 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 8,133 women, take 2,019 from our lounges and add 6,114 net, 114 above the 6,000 line.
  <small>Net new women: 6113.8616; New lounge would serve: 8132.5994; Taken from our lounges: 2018.7377; Size gap: 114</small>
- **demand**: That is more than a typical lounge would serve at 83% of Abu Dhabi salon sites, 87th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8289; Demand gap: 0.3289; Demand percentile UAE-wide: 0.8655; New lounge would serve: 8132.5994</small>
- **cost**: Shop rent of AED 1,638/m² a year gives a rent ratio of 0.85 against the median Abu Dhabi salon site, 0.15 short of the 1 line; dearer than 50% of UAE salon sites.
  <small>Rent ratio: 0.851; Rent gap: -0.149; Rent percentile UAE-wide: 0.4969; Shop rent in the area: 1638.0</small>
- **reach**: The nearest lounge, baniyas, is 6.3 km away in a straight line.
  <small>Distance to nearest lounge: 6.3203; Nearest lounge: baniyas</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-zawarah-ajman — **WATCH** (ai)

**WATCH Al Zawarah: a new lounge would add 5,595 net new women, 405 short of the 6,000 line.**

- **size**: A new lounge would serve 5,620 women, take 25 from our lounges and add 5,595 net, 405 short of the 6,000 line.
  <small>Net new women: 5595.1299; New lounge would serve: 5619.8438; Taken from our lounges: 24.7139; Size gap: -405</small>
- **demand**: That is more than a typical lounge would serve at 76% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 76th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7578; Demand gap: 0.2578; Demand percentile UAE-wide: 0.7578; New lounge would serve: 5619.8438</small>
- **cost**: Shop rent of AED 589/m² a year gives a rent ratio of 1.28 against the median Ajman salon site, 0.28 above the 1 line; dearer than 2% of UAE salon sites.
  <small>Rent ratio: 1.278; Rent gap: 0.278; Rent percentile UAE-wide: 0.0169; Shop rent in the area: 589.2</small>
- **reach**: The nearest lounge, al-jada, is 12.1 km away in a straight line.
  <small>Distance to nearest lounge: 12.1381; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### eastern-mahadir-abu-dhabi — **WATCH** (ai)

**WATCH Eastern Mahadir: a new lounge would add 4,277 net new women, 1,723 short of the 6,000 line.**

- **size**: A new lounge would serve 4,277 women and take almost none from our lounges, so 4,277 are net new, 1,723 short of the 6,000 line.
  <small>Net new women: 4276.9897; New lounge would serve: 4276.9897; Taken from our lounges: 0.0; Size gap: -1723</small>
- **demand**: That is more than a typical lounge would serve at 53% of Abu Dhabi salon sites, 68th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.5263; Demand gap: 0.0263; Demand percentile UAE-wide: 0.675; New lounge would serve: 4276.9897</small>
- **cost**: Shop rent of AED 165/m² a year gives a rent ratio of 8.45 against the median Abu Dhabi salon site, 7.45 above the 1 line; among the cheapest UAE salon sites.
  <small>Rent ratio: 8.4485; Rent gap: 7.4485; Rent percentile UAE-wide: 0.0; Shop rent in the area: 165.0</small>
- **reach**: The nearest lounge, al-dhafra, is 67.6 km away: Eastern Mahadir is white space for the network.
  <small>Distance to nearest lounge: 67.6068; Nearest lounge: al-dhafra</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### dubai-investments-park-dubai — **WATCH** (ai)

**WATCH Dubai Investments Park: a new lounge would add 4,464 net new women, 1,536 short of the 6,000 line.**

- **size**: A new lounge would serve 4,496 women, take 32 from our lounges and add 4,464 net, 1,536 short of the 6,000 line.
  <small>Net new women: 4463.9488; New lounge would serve: 4495.9199; Taken from our lounges: 31.9711; Size gap: -1536</small>
- **demand**: That is more than a typical lounge would serve at 96% of Dubai salon sites, 70th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9588; Demand gap: 0.4588; Demand percentile UAE-wide: 0.6972; New lounge would serve: 4495.9199</small>
- **cost**: Shop rent of AED 1,096/m² a year gives a rent ratio of 1.96 against the median Dubai salon site, 0.96 above the 1 line; dearer than 16% of UAE salon sites.
  <small>Rent ratio: 1.9649; Rent gap: 0.9649; Rent percentile UAE-wide: 0.1558; Shop rent in the area: 1096.0</small>
- **reach**: The nearest lounge, jumeirah-park, is 7.5 km away in a straight line.
  <small>Distance to nearest lounge: 7.5304; Nearest lounge: jumeirah-park</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-helio-ajman — **WATCH** (ai)

**WATCH Al Helio: a new lounge would add about 18,000 net new women, but its rent is dearer than the median Ajman salon site.**

- **size**: A new lounge would serve 18,070 women, take 112 from our lounges and add 17,958 net, 11,958 above the 6,000 line.
  <small>Net new women: 17957.6145; New lounge would serve: 18070.0403; Taken from our lounges: 112.4258; Size gap: 11958</small>
- **demand**: That is more than a typical lounge would serve at 99% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 99th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9893; Demand gap: 0.4893; Demand percentile UAE-wide: 0.9893; New lounge would serve: 18070.0403</small>
- **cost**: Shop rent of AED 1,118/m² a year gives a rent ratio of 0.67 against the median Ajman salon site, 0.33 short of the 1 line; dearer than 18% of UAE salon sites.
  <small>Rent ratio: 0.6735; Rent gap: -0.3265; Rent percentile UAE-wide: 0.1799; Shop rent in the area: 1118.0</small>
- **reach**: The nearest lounge, al-jada, is 14.6 km away in a straight line.
  <small>Distance to nearest lounge: 14.6234; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-rashidiya-dubai — **WATCH** (ai)

**WATCH Al Rashidiya: a new lounge would add 3,972 net new women, 2,028 short of the 6,000 line.**

- **size**: A new lounge would serve 4,072 women, take 100 from our lounges and add 3,972 net, 2,028 short of the 6,000 line.
  <small>Net new women: 3972.2813; New lounge would serve: 4072.3564; Taken from our lounges: 100.0751; Size gap: -2028</small>
- **demand**: That is more than a typical lounge would serve at 94% of Dubai salon sites, 66th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9364; Demand gap: 0.4364; Demand percentile UAE-wide: 0.6625; New lounge would serve: 4072.3564</small>
- **cost**: Shop rent of AED 1,696/m² a year gives a rent ratio of 1.27 against the median Dubai salon site, 0.27 above the 1 line; dearer than 51% of UAE salon sites.
  <small>Rent ratio: 1.2698; Rent gap: 0.2698; Rent percentile UAE-wide: 0.5111; Shop rent in the area: 1696.0</small>
- **reach**: The nearest lounge, mirdif-35, is 4.7 km away in a straight line.
  <small>Distance to nearest lounge: 4.7208; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-marfa-abu-dhabi — **WATCH** (ai)

**WATCH Al Marfa: a new lounge would add 4,489 net new women, 1,511 short of the 6,000 line.**

- **size**: A new lounge would serve 4,489 women and take almost none from our lounges, so 4,489 are net new, 1,511 short of the 6,000 line.
  <small>Net new women: 4489.2486; New lounge would serve: 4489.2486; Taken from our lounges: 0.0; Size gap: -1511</small>
- **demand**: That is more than a typical lounge would serve at 58% of Abu Dhabi salon sites, 70th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.5789; Demand gap: 0.0789; Demand percentile UAE-wide: 0.6963; New lounge would serve: 4489.2486</small>
- **cost**: Shop rent of AED 628/m² a year gives a rent ratio of 2.22 against the median Abu Dhabi salon site, 1.22 above the 1 line; dearer than 2% of UAE salon sites.
  <small>Rent ratio: 2.2197; Rent gap: 1.2197; Rent percentile UAE-wide: 0.0223; Shop rent in the area: 628.0</small>
- **reach**: The nearest lounge, al-dhafra, is 56.3 km away: Al Marfa is white space for the network.
  <small>Distance to nearest lounge: 56.3275; Nearest lounge: al-dhafra</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### mbazzarah-al-khadra-abu-dhabi — **WATCH** (ai)

**WATCH Mbazzarah Al Khadra: a new lounge would add about 10,700 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 10,973 women, take 280 from our lounges and add 10,693 net, 4,693 above the 6,000 line.
  <small>Net new women: 10692.978; New lounge would serve: 10972.6463; Taken from our lounges: 279.6683; Size gap: 4693</small>
- **demand**: That is more than a typical lounge would serve at 97% of Abu Dhabi salon sites, 95th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9704; Demand gap: 0.4704; Demand percentile UAE-wide: 0.9466; New lounge would serve: 10972.6463</small>
- **cost**: Shop rent of AED 1,879/m² a year gives a rent ratio of 0.74 against the median Abu Dhabi salon site, 0.26 short of the 1 line; dearer than 58% of UAE salon sites.
  <small>Rent ratio: 0.7419; Rent gap: -0.2581; Rent percentile UAE-wide: 0.5779; Shop rent in the area: 1879.0</small>
- **reach**: The nearest lounge, al-ain, is 17.2 km away in a straight line.
  <small>Distance to nearest lounge: 17.1919; Nearest lounge: al-ain</small>
- **data_gap**: Our salon search covered only 46% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.4643; Coverage needed: 0.5; Coverage gap: -0.0357</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-twar-dubai — **WATCH** (ai)

**WATCH Al Twar: a new lounge would add 4,851 net new women, 1,149 short of the 6,000 line.**

- **size**: A new lounge would serve 4,983 women, take 133 from our lounges and add 4,851 net, 1,149 short of the 6,000 line.
  <small>Net new women: 4850.6375; New lounge would serve: 4983.443; Taken from our lounges: 132.8055; Size gap: -1149</small>
- **demand**: That is more than a typical lounge would serve at 97% of Dubai salon sites, 72nd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9708; Demand gap: 0.4708; Demand percentile UAE-wide: 0.7248; New lounge would serve: 4983.443</small>
- **cost**: Shop rent of AED 2,099/m² a year gives a rent ratio of 1.03 against the median Dubai salon site, 0.03 above the 1 line; dearer than 65% of UAE salon sites.
  <small>Rent ratio: 1.026; Rent gap: 0.026; Rent percentile UAE-wide: 0.6527; Shop rent in the area: 2099.0</small>
- **reach**: The nearest lounge, mirdif-35, is 5.4 km away in a straight line.
  <small>Distance to nearest lounge: 5.3922; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### shiab-al-ashkhar-abu-dhabi — **WATCH** (ai)

**WATCH Shiab Al Ashkhar: a new lounge would add about 7,700 net new women, but its rent is dearer than the median Abu Dhabi salon site.**

- **size**: A new lounge would serve 8,066 women, take 365 from our lounges and add 7,701 net, 1,701 above the 6,000 line.
  <small>Net new women: 7700.8044; New lounge would serve: 8065.5252; Taken from our lounges: 364.7208; Size gap: 1701</small>
- **demand**: That is more than a typical lounge would serve at 83% of Abu Dhabi salon sites, 86th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8289; Demand gap: 0.3289; Demand percentile UAE-wide: 0.8611; New lounge would serve: 8065.5252</small>
- **cost**: Shop rent of AED 2,809/m² a year gives a rent ratio of 0.50 against the median Abu Dhabi salon site, 0.50 short of the 1 line; dearer than 90% of UAE salon sites.
  <small>Rent ratio: 0.4963; Rent gap: -0.5037; Rent percentile UAE-wide: 0.902; Shop rent in the area: 2809.0</small>
- **reach**: The nearest lounge, al-ain, is 10.8 km away in a straight line.
  <small>Distance to nearest lounge: 10.8031; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### umm-ramool-dubai — **WATCH** (ai)

**WATCH Umm Ramool: a new lounge would add 4,383 net new women, 1,617 short of the 6,000 line.**

- **size**: A new lounge would serve 4,493 women, take 110 from our lounges and add 4,383 net, 1,617 short of the 6,000 line.
  <small>Net new women: 4383.1732; New lounge would serve: 4492.8602; Taken from our lounges: 109.687; Size gap: -1617</small>
- **demand**: That is more than a typical lounge would serve at 96% of Dubai salon sites, 70th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9588; Demand gap: 0.4588; Demand percentile UAE-wide: 0.6972; New lounge would serve: 4492.8602</small>
- **cost**: Shop rent of AED 1,984/m² a year gives a rent ratio of 1.09 against the median Dubai salon site, 0.09 above the 1 line; dearer than 60% of UAE salon sites.
  <small>Rent ratio: 1.0854; Rent gap: 0.0854; Rent percentile UAE-wide: 0.5975; Shop rent in the area: 1984.0</small>
- **reach**: The nearest lounge, mirdif-35, is 6.5 km away in a straight line.
  <small>Distance to nearest lounge: 6.5454; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-garhoud-dubai — **WATCH** (ai)

**WATCH Al Garhoud: a new lounge would add 3,142 net new women, 2,858 short of the 6,000 line.**

- **size**: A new lounge would serve 3,206 women, take 63 from our lounges and add 3,142 net, 2,858 short of the 6,000 line.
  <small>Net new women: 3142.3205; New lounge would serve: 3205.7423; Taken from our lounges: 63.4218; Size gap: -2858</small>
- **demand**: That is more than a typical lounge would serve at 81% of Dubai salon sites, 56th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8058; Demand gap: 0.3058; Demand percentile UAE-wide: 0.5637; New lounge would serve: 3205.7423</small>
- **cost**: Shop rent of AED 1,237/m² a year gives a rent ratio of 1.74 against the median Dubai salon site, 0.74 above the 1 line; dearer than 28% of UAE salon sites.
  <small>Rent ratio: 1.7409; Rent gap: 0.7409; Rent percentile UAE-wide: 0.276; Shop rent in the area: 1237.0</small>
- **reach**: The nearest lounge, mirdif-35, is 8.5 km away in a straight line.
  <small>Distance to nearest lounge: 8.5465; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### masakin-abu-dhabi — **WATCH** (ai)

**WATCH Masakin: a new lounge would add 5,680 net new women, 320 short of the 6,000 line.**

- **size**: A new lounge would serve 5,780 women, take 101 from our lounges and add 5,680 net, 320 short of the 6,000 line.
  <small>Net new women: 5679.9659; New lounge would serve: 5780.4674; Taken from our lounges: 100.5015; Size gap: -320</small>
- **demand**: That is more than a typical lounge would serve at 69% of Abu Dhabi salon sites, 76th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.6875; Demand gap: 0.1875; Demand percentile UAE-wide: 0.764; New lounge would serve: 5780.4674</small>
- **cost**: Shop rent of AED 1,168/m² a year is the Abu Dhabi median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 22% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1168.0; Rent percentile UAE-wide: 0.2155</small>
- **reach**: The nearest lounge, al-ain, is 24.9 km away in a straight line.
  <small>Distance to nearest lounge: 24.8576; Nearest lounge: al-ain</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-khaznah-abu-dhabi — **WATCH** (ai)

**WATCH Al Khaznah: a new lounge would add 4,695 net new women, 1,305 short of the 6,000 line.**

- **size**: A new lounge would serve 4,748 women, take 53 from our lounges and add 4,695 net, 1,305 short of the 6,000 line.
  <small>Net new women: 4695.0291; New lounge would serve: 4747.9618; Taken from our lounges: 52.9327; Size gap: -1305</small>
- **demand**: That is more than a typical lounge would serve at 60% of Abu Dhabi salon sites, 71st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.5987; Demand gap: 0.0987; Demand percentile UAE-wide: 0.7106; New lounge would serve: 4747.9618</small>
- **cost**: Shop rent of AED 959/m² a year gives a rent ratio of 1.45 against the median Abu Dhabi salon site, 0.45 above the 1 line; dearer than 9% of UAE salon sites.
  <small>Rent ratio: 1.4536; Rent gap: 0.4536; Rent percentile UAE-wide: 0.0944; Shop rent in the area: 959.0</small>
- **reach**: The nearest lounge, al-falah, is 47.8 km away: Al Khaznah is white space for the network.
  <small>Distance to nearest lounge: 47.7845; Nearest lounge: al-falah</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### central-district-abu-dhabi — **WATCH** (ai)

**WATCH Central District: a new lounge would add 4,849 net new women, 1,151 short of the 6,000 line.**

- **size**: A new lounge would serve 5,091 women, take 242 from our lounges and add 4,849 net, 1,151 short of the 6,000 line.
  <small>Net new women: 4848.703; New lounge would serve: 5091.0618; Taken from our lounges: 242.3588; Size gap: -1151</small>
- **demand**: That is more than a typical lounge would serve at 64% of Abu Dhabi salon sites, 73rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.6382; Demand gap: 0.1382; Demand percentile UAE-wide: 0.732; New lounge would serve: 5091.0618</small>
- **cost**: Shop rent of AED 1,112/m² a year gives a rent ratio of 1.25 against the median Abu Dhabi salon site, 0.25 above the 1 line; dearer than 16% of UAE salon sites.
  <small>Rent ratio: 1.2536; Rent gap: 0.2536; Rent percentile UAE-wide: 0.1638; Shop rent in the area: 1112.0</small>
- **reach**: The nearest lounge, al-ain, is 12.0 km away in a straight line.
  <small>Distance to nearest lounge: 12.0223; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-sarouj-abu-dhabi — **WATCH** (ai)

**WATCH Al Sarouj: a new lounge would add 5,379 net new women, 621 short of the 6,000 line.**

- **size**: A new lounge would serve 5,557 women, take 178 from our lounges and add 5,379 net, 621 short of the 6,000 line.
  <small>Net new women: 5378.8606; New lounge would serve: 5557.059; Taken from our lounges: 178.1984; Size gap: -621</small>
- **demand**: That is more than a typical lounge would serve at 66% of Abu Dhabi salon sites, 75th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.6645; Demand gap: 0.1645; Demand percentile UAE-wide: 0.7542; New lounge would serve: 5557.059</small>
- **cost**: Shop rent of AED 680/m² a year gives a rent ratio of 2.05 against the median Abu Dhabi salon site, 1.05 above the 1 line; dearer than 3% of UAE salon sites.
  <small>Rent ratio: 2.05; Rent gap: 1.05; Rent percentile UAE-wide: 0.0303; Shop rent in the area: 680.0</small>
- **reach**: The nearest lounge, al-ain, is 14.3 km away in a straight line.
  <small>Distance to nearest lounge: 14.2841; Nearest lounge: al-ain</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### nadd-al-hamar-dubai — **WATCH** (ai)

**WATCH Nadd Al Hamar: a new lounge would add 3,033 net new women, 2,967 short of the 6,000 line.**

- **size**: A new lounge would serve 3,100 women, take 67 from our lounges and add 3,033 net, 2,967 short of the 6,000 line.
  <small>Net new women: 3033.3343; New lounge would serve: 3100.0645; Taken from our lounges: 66.7302; Size gap: -2967</small>
- **demand**: That is more than a typical lounge would serve at 79% of Dubai salon sites, 55th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7852; Demand gap: 0.2852; Demand percentile UAE-wide: 0.5494; New lounge would serve: 3100.0645</small>
- **cost**: Shop rent of AED 1,696/m² a year gives a rent ratio of 1.27 against the median Dubai salon site, 0.27 above the 1 line; dearer than 51% of UAE salon sites.
  <small>Rent ratio: 1.2698; Rent gap: 0.2698; Rent percentile UAE-wide: 0.5111; Shop rent in the area: 1696.0</small>
- **reach**: The nearest lounge, nad-al-sheba, is 4.8 km away in a straight line.
  <small>Distance to nearest lounge: 4.7871; Nearest lounge: nad-al-sheba</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### dubai-investment-park-2-dubai — **WATCH** (ai)

**WATCH Dubai Investment Park 2: a new lounge would add 3,634 net new women, 2,366 short of the 6,000 line.**

- **size**: A new lounge would serve 3,663 women, take 29 from our lounges and add 3,634 net, 2,366 short of the 6,000 line.
  <small>Net new women: 3634.1548; New lounge would serve: 3663.0999; Taken from our lounges: 28.9451; Size gap: -2366</small>
- **demand**: That is more than a typical lounge would serve at 88% of Dubai salon sites, 62nd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8797; Demand gap: 0.3797; Demand percentile UAE-wide: 0.6198; New lounge would serve: 3663.0999</small>
- **cost**: Shop rent of AED 1,096/m² a year gives a rent ratio of 1.96 against the median Dubai salon site, 0.96 above the 1 line; dearer than 16% of UAE salon sites.
  <small>Rent ratio: 1.9649; Rent gap: 0.9649; Rent percentile UAE-wide: 0.1558; Shop rent in the area: 1096.0</small>
- **reach**: The nearest lounge, jumeirah-park, is 8.4 km away in a straight line.
  <small>Distance to nearest lounge: 8.4028; Nearest lounge: jumeirah-park</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-rashidiya-ajman — **WATCH** (ai)

**WATCH Al Rashidiya: a new lounge would add about 6,900 net new women, but its rent is dearer than the median Ajman salon site.**

- **size**: A new lounge would serve 6,992 women, take 130 from our lounges and add 6,862 net, 862 above the 6,000 line.
  <small>Net new women: 6861.9762; New lounge would serve: 6991.7181; Taken from our lounges: 129.742; Size gap: 862</small>
- **demand**: That is more than a typical lounge would serve at 81% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 81st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8139; Demand gap: 0.3139; Demand percentile UAE-wide: 0.8139; New lounge would serve: 6991.7181</small>
- **cost**: Shop rent of AED 972/m² a year gives a rent ratio of 0.77 against the median Ajman salon site, 0.23 short of the 1 line; dearer than 10% of UAE salon sites.
  <small>Rent ratio: 0.7745; Rent gap: -0.2255; Rent percentile UAE-wide: 0.0953; Shop rent in the area: 972.3</small>
- **reach**: The nearest lounge, zawaya-walk, is 7.9 km away in a straight line.
  <small>Distance to nearest lounge: 7.854; Nearest lounge: zawaya-walk</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### nahil-abu-dhabi — **WATCH** (ai)

**WATCH Nahil: a new lounge would add 4,524 net new women, 1,476 short of the 6,000 line.**

- **size**: A new lounge would serve 4,526 women, take 2 from our lounges and add 4,524 net, 1,476 short of the 6,000 line.
  <small>Net new women: 4523.6815; New lounge would serve: 4526.089; Taken from our lounges: 2.4074; Size gap: -1476</small>
- **demand**: That is more than a typical lounge would serve at 58% of Abu Dhabi salon sites, 70th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.5822; Demand gap: 0.0822; Demand percentile UAE-wide: 0.699; New lounge would serve: 4526.089</small>
- **cost**: Shop rent of AED 429/m² a year gives a rent ratio of 3.25 against the median Abu Dhabi salon site, 2.25 above the 1 line; among the cheapest UAE salon sites.
  <small>Rent ratio: 3.2494; Rent gap: 2.2494; Rent percentile UAE-wide: 0.0027; Shop rent in the area: 429.0</small>
- **reach**: The nearest lounge, al-ain, is 35.9 km away: Nahil is white space for the network.
  <small>Distance to nearest lounge: 35.9305; Nearest lounge: al-ain</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### dihan-abu-dhabi — **WATCH** (ai)

**WATCH Dihan: a new lounge would add 5,006 net new women, 994 short of the 6,000 line.**

- **size**: A new lounge would serve 5,012 women, take 6 from our lounges and add 5,006 net, 994 short of the 6,000 line.
  <small>Net new women: 5005.6902; New lounge would serve: 5012.1697; Taken from our lounges: 6.4795; Size gap: -994</small>
- **demand**: That is more than a typical lounge would serve at 63% of Abu Dhabi salon sites, 73rd percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.6283; Demand gap: 0.1283; Demand percentile UAE-wide: 0.7266; New lounge would serve: 5012.1697</small>
- **cost**: Shop rent of AED 991/m² a year gives a rent ratio of 1.41 against the median Abu Dhabi salon site, 0.41 above the 1 line; dearer than 10% of UAE salon sites.
  <small>Rent ratio: 1.4067; Rent gap: 0.4067; Rent percentile UAE-wide: 0.1042; Shop rent in the area: 991.0</small>
- **reach**: The nearest lounge, al-falah, is 38.1 km away: Dihan is white space for the network.
  <small>Distance to nearest lounge: 38.0781; Nearest lounge: al-falah</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-qou-abu-dhabi — **WATCH** (ai)

**WATCH Al Qou': a new lounge would add 3,192 net new women, 2,808 short of the 6,000 line.**

- **size**: A new lounge would serve 3,192 women and take almost none from our lounges, so 3,192 are net new, 2,808 short of the 6,000 line.
  <small>Net new women: 3192.2909; New lounge would serve: 3192.2909; Taken from our lounges: 0.0; Size gap: -2808</small>
- **demand**: That is more than a typical lounge would serve at 44% of Abu Dhabi salon sites, 56th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.4441; Demand gap: -0.0559; Demand percentile UAE-wide: 0.5637; New lounge would serve: 3192.2909</small>
- **cost**: Shop rent of AED 1,658/m² a year gives a rent ratio of 0.84 against the median Abu Dhabi salon site, 0.16 short of the 1 line; dearer than 51% of UAE salon sites.
  <small>Rent ratio: 0.8408; Rent gap: -0.1592; Rent percentile UAE-wide: 0.5058; Shop rent in the area: 1658.0</small>
- **reach**: The nearest lounge, al-ain, is 92.4 km away: Al Qou' is white space for the network.
  <small>Distance to nearest lounge: 92.3809; Nearest lounge: al-ain</small>
- **data_gap**: Our salon search covered only 0% of the women here (a confident call needs 50%), so part of the competition is imputed.
  <small>Competitor data coverage: 0.0; Coverage needed: 0.5; Coverage gap: -0.5</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-jaddaf-dubai — **WATCH** (ai)

**WATCH Al Jaddaf: a new lounge would add 3,340 net new women, 2,660 short of the 6,000 line.**

- **size**: A new lounge would serve 3,403 women, take 62 from our lounges and add 3,340 net, 2,660 short of the 6,000 line.
  <small>Net new women: 3340.143; New lounge would serve: 3402.5169; Taken from our lounges: 62.3739; Size gap: -2660</small>
- **demand**: That is more than a typical lounge would serve at 83% of Dubai salon sites, 59th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8333; Demand gap: 0.3333; Demand percentile UAE-wide: 0.5868; New lounge would serve: 3402.5169</small>
- **cost**: Shop rent of AED 1,639/m² a year gives a rent ratio of 1.31 against the median Dubai salon site, 0.31 above the 1 line; dearer than 50% of UAE salon sites.
  <small>Rent ratio: 1.3139; Rent gap: 0.3139; Rent percentile UAE-wide: 0.4969; Shop rent in the area: 1639.0</small>
- **reach**: The nearest lounge, city-walk, is 6.7 km away in a straight line.
  <small>Distance to nearest lounge: 6.7442; Nearest lounge: city-walk</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### madinat-al-riyad-abu-dhabi — **WATCH** (ai)

**WATCH Madinat Al Riyad: a new lounge would add 5,116 net new women, 884 short of the 6,000 line.**

- **size**: A new lounge would serve 6,876 women, take 1,760 from our lounges and add 5,116 net, 884 short of the 6,000 line.
  <small>Net new women: 5116.0955; New lounge would serve: 6876.2738; Taken from our lounges: 1760.1783; Size gap: -884</small>
- **demand**: That is more than a typical lounge would serve at 78% of Abu Dhabi salon sites, 81st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.7829; Demand gap: 0.2829; Demand percentile UAE-wide: 0.8121; New lounge would serve: 6876.2738</small>
- **cost**: Shop rent of AED 2,822/m² a year gives a rent ratio of 0.49 against the median Abu Dhabi salon site, 0.51 short of the 1 line; dearer than 90% of UAE salon sites.
  <small>Rent ratio: 0.494; Rent gap: -0.506; Rent percentile UAE-wide: 0.9029; Shop rent in the area: 2822.0</small>
- **reach**: The nearest lounge, al-falah, is 10.3 km away in a straight line.
  <small>Distance to nearest lounge: 10.2547; Nearest lounge: al-falah</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-mizhar-2-dubai — **WATCH** (ai)

**WATCH Al Mizhar 2: a new lounge would add 4,411 net new women, 1,589 short of the 6,000 line.**

- **size**: A new lounge would serve 4,551 women, take 140 from our lounges and add 4,411 net, 1,589 short of the 6,000 line.
  <small>Net new women: 4411.17; New lounge would serve: 4551.0769; Taken from our lounges: 139.9069; Size gap: -1589</small>
- **demand**: That is more than a typical lounge would serve at 96% of Dubai salon sites, 70th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9622; Demand gap: 0.4622; Demand percentile UAE-wide: 0.7017; New lounge would serve: 4551.0769</small>
- **cost**: Shop rent of AED 3,502/m² a year gives a rent ratio of 0.61 against the median Dubai salon site, 0.39 short of the 1 line; dearer than 95% of UAE salon sites.
  <small>Rent ratio: 0.6149; Rent gap: -0.3851; Rent percentile UAE-wide: 0.9475; Shop rent in the area: 3502.0</small>
- **reach**: The nearest lounge, mirdif-35, is 3.6 km away in a straight line.
  <small>Distance to nearest lounge: 3.6387; Nearest lounge: mirdif-35</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-kheeran-dubai — **WATCH** (ai)

**WATCH Al Kheeran: a new lounge would add 3,558 net new women, 2,442 short of the 6,000 line.**

- **size**: A new lounge would serve 3,631 women, take 73 from our lounges and add 3,558 net, 2,442 short of the 6,000 line.
  <small>Net new women: 3557.5706; New lounge would serve: 3630.8237; Taken from our lounges: 73.2532; Size gap: -2442</small>
- **demand**: That is more than a typical lounge would serve at 87% of Dubai salon sites, 61st percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.8711; Demand gap: 0.3711; Demand percentile UAE-wide: 0.6144; New lounge would serve: 3630.8237</small>
- **cost**: Shop rent of AED 2,746/m² a year gives a rent ratio of 0.78 against the median Dubai salon site, 0.22 short of the 1 line; dearer than 89% of UAE salon sites.
  <small>Rent ratio: 0.7842; Rent gap: -0.2158; Rent percentile UAE-wide: 0.8949; Shop rent in the area: 2746.0</small>
- **reach**: The nearest lounge, nad-al-sheba, is 6.6 km away in a straight line.
  <small>Distance to nearest lounge: 6.6295; Nearest lounge: nad-al-sheba</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

### al-marmoom-dubai — **WATCH** (ai)

**WATCH Al Marmoom: a new lounge would add 4,493 net new women, 1,507 short of the 6,000 line.**

- **size**: A new lounge would serve 4,493 women and take almost none from our lounges, so 4,493 are net new, 1,507 short of the 6,000 line.
  <small>Net new women: 4492.5799; New lounge would serve: 4492.7294; Taken from our lounges: 0.1495; Size gap: -1507</small>
- **demand**: That is more than a typical lounge would serve at 96% of Dubai salon sites, 70th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9588; Demand gap: 0.4588; Demand percentile UAE-wide: 0.6972; New lounge would serve: 4492.7294</small>
- **cost**: Shop rent of AED 1,985/m² a year is the Dubai median standing in for cells with no rent of their own, not an observation of this place, so the rent test is neutral; for context it is dearer than 60% of UAE salon sites.
  <small>Rent is the emirate median: True; Shop rent in the area: 1985.0; Rent percentile UAE-wide: 0.5975</small>
- **reach**: The nearest lounge, nad-al-sheba, is 22.7 km away in a straight line.
  <small>Distance to nearest lounge: 22.7169; Nearest lounge: nad-al-sheba</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median, unless that rent is only the emirate median standing in for cells without one: then the rent test is neutral and the call low confidence._

### al-muwaihat-ajman — **WATCH** (ai)

**WATCH Al Muwaihat: a new lounge would add about 11,700 net new women, but its rent is dearer than the median Ajman salon site.**

- **size**: A new lounge would serve 11,954 women, take 238 from our lounges and add 11,716 net, 5,716 above the 6,000 line.
  <small>Net new women: 11715.7382; New lounge would serve: 11953.9612; Taken from our lounges: 238.223; Size gap: 5716</small>
- **demand**: That is more than a typical lounge would serve at 96% of UAE salon sites (Ajman has under 50, so ranked UAE-wide), 96th percentile UAE-wide; GROW needs 50%.
  <small>Site demand percentile: 0.9626; Demand gap: 0.4626; Demand percentile UAE-wide: 0.9626; New lounge would serve: 11953.9612</small>
- **cost**: Shop rent of AED 821/m² a year gives a rent ratio of 0.92 against the median Ajman salon site, 0.08 short of the 1 line; dearer than 8% of UAE salon sites.
  <small>Rent ratio: 0.9174; Rent gap: -0.0826; Rent percentile UAE-wide: 0.0766; Shop rent in the area: 820.8</small>
- **reach**: The nearest lounge, al-jada, is 7.3 km away in a straight line.
  <small>Distance to nearest lounge: 7.2531; Nearest lounge: al-jada</small>

_Each area is a what-if: open a typical lounge here and count the women it adds to the network, net of what it takes from our own lounges. GROW also needs the site to out-serve at least half of its emirate's salon sites and a rent no dearer than their median; the UAE-wide percentiles are context._

In [7]:
table("area", areas[0][1])

,Value,Unit,Threshold,What it means
Factor,,,,
Women 15+,"281,946",women,"SKIP under 5,000",Women aged 15+ living in the area's cells (raw).
Addressable women 15+,"281,946",women,—,"Catchment women times an affluence weight (observed median rent vs the women-weighted median, to the affluence elast..."
Affluence rent,n/a (missing),AED/yr,—,"Median annual household rent (DLD Ejari contracts, Jul-Oct 2026), weighted by women, over the cells with an observed..."
Affluence coverage,0%,% of women,"Under 50%: affluence mostly unknown, weighted neutral",Share of the women here living in cells with an observed rent. The rest are weighted neutral: affluence unknown. Dub...
Cells,89,count,—,Populated ~2 km cells in the area (every unreached cell with this OSM place name).
Worker housing,12%,% of adults,GROW needs under 50%,Share of the area's adults living in worker housing (OSM industrial land use).
Premium salons,107,count,—,Premium salons found in the area's searched cells.
Premium saturation,116,reviews per 1k women,"Unsaturated under 150 (context, not a test)","Premium salons' Google reviews (scaled up for missed salons) per 1,000 women in the searched cells: the same measure..."
Shop rent in the area,"1,121",AED/m²/yr,—,"Women-weighted median shop rent over the area's cells (DLD in Dubai, ADREC in Abu Dhabi, listings in the northern em..."
Women per AED 1k of rent,"1,677",women,—,"Addressable women per AED 1,000 of annual rent for a 150 m² unit (assumed): the unit size sets the level, never the ..."
New lounge would serve,"13,176",women,—,What-if: women a typical new lounge here would serve (Huff).
Taken from our lounges,368,women,—,"What-if: of those, women it would take from our existing lounges."
Net new women,"12,808",women,"GROW needs 6,000; WATCH from 3,000",What-if: women a new lounge here adds to the network (served − taken).
Unserved women,"7,490",women,—,Addressable women no premium salon serves today (Huff).
Site demand percentile,90%,% of salon sites,"Demand score: 0% of salon sites → 0, 100% of salon sites → 1; weight 1",Share of the reference salon sites in its emirate (UAE-wide under 50) that a typical lounge would out-serve at this ...
Demand ranked among,Sharjah,,—,"Whose salon sites the demand percentile ranks against: the site's emirate, or UAE when the emirate has under 50 refe..."
Demand percentile UAE-wide,98%,% of UAE salon sites,—,"The same, against all 1,123 UAE reference salon sites. Context, not scored."
Rent ratio,1,,"Cost score: 0.62 → 0, 1.43 → 1; weight 1",Median shop rent at the reference salon sites in its emirate ÷ this site's shop rent: above 1 is cheaper than a typi...
Rent percentile UAE-wide,20%,% of UAE salon sites,—,"Share of the UAE reference salon sites with a lower shop rent (higher = dearer). Context, not scored."
Site cost,258,AED 1k/yr,—,"Shop rent x 150 m² (assumed unit) + fit-out of AED 3,000/m² over 5 years (assumed)."
Competitor data coverage,99%,% of women,GROW needs 50%,Share of the area's women in cells our salon search covered.
Nearest lounge,al-jada,,—,"Closest open, scored Bedashing lounge."
Distance to nearest lounge,2.48,km,—,"Straight-line distance to the closest open, scored lounge (an area can sit inside a lounge's catchment: the what-if ..."
Big enough,yes,yes/no,"GROW needs big enough, rent ratio 1 or more (or unknown) and demand percentile 50% or more","A new lounge here would add at least 6,000 net new women and worker housing is under 50% of adults."
Unsaturated,yes,yes/no,"Context, not a test",Fewer than 150 premium reviews per 1k women (n/a when too little of the area was searched). Context only: competitio...
Confidence,high,,—,Low within 10% of the net-new-women line or with under 50% of the women searched; high 20%+ from the line; else medium.
Size gap,"6,808",net new women,"GROW needs 0 or more (line 6,000)","Net new women minus the size line: positive is headroom above it, negative is how many more a new lounge would need ..."
Demand gap,40%,% of salon sites,GROW needs 0 or more,"Site demand percentile minus 50%: GROW needs 0 or more, else a big-enough area is WATCH."
Rent gap,0,,"GROW needs 0 or more (or no rent known, or the emirate-median fallback)","Rent ratio minus 1 (the median salon site in its emirate): GROW needs 0 or more, else a big-enough area is WATCH. n/..."
Saturation gap,33.58,reviews per 1k women,"Context, not a test (line 150)","Saturation line minus premium saturation: positive is room under the line, negative is how far over it. Context only..."
Worker-housing gap,38%,% of adults,GROW needs above 0 (cap 50%),Worker-housing cap minus worker share: negative means over the cap.
Coverage gap,49%,% of women,Under 0: low confidence (needs 50%),Competitor data coverage minus the coverage needed: negative means too little was searched to GROW.

## Play with it

Change a number and see the fallback: the cache key is a hash of the fact sheet, so any change
means the template is served instead of the cached AI text (and `verify` would reject the old
text anyway).

In [8]:
k, sid, a, f = next(s for s in subjects if s[1] == "al-barsha")
changed = {**f, "catchment_women": f["catchment_women"] + 1}
print(explain(k, sid, a, changed, cache=cache).source, "<- template, because one number changed")

template <- template, because one number changed